### ISSUE TITLE
Issue cannot be blank in all cases

### ISSUE THREAD

**Issue by dagomar** [dhanasingh/redmine_wktime#1]
I'm having a problem when I choose 'Add row' in the timesheet, I don't have the possibility to have a blank issue:

![selection_129](https://cloud.githubusercontent.com/assets/115586/4020080/2367c650-2aa3-11e4-93b5-971090027dd8.png)

The same happens if I switch between projects, so, if I choose another project, I then cannot choose empty for issue :'(

**Comment by wallabom** [comment]
I just realize that I have the same issue and I created a new error : https://github.com/dhanasingh/redmine_wktime/issues/8

I confirm that even if I have the option ticked in the configuration, I cannot have a blank issue selected. I cannot log the time to the project straight. See the screenshot here 
![non_blank2](https://cloud.githubusercontent.com/assets/655793/5779034/c73cfbbe-9d9f-11e4-96b5-579d62699c8a.png)

The plugin is configured with : 
select name,value from settings where id = 60 order by 1 desc

name	value
plugin_redmine_wktime	--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess/nwktime_previous_template_week: '1'/nwktime_allow_filter_issue: '1'/nwktime_allow_blank_issue: '1'/nwktime_enter_comment_in_row: '1'/nwktime_use_detail_popup: '1'/nwktime_project_dd_width: '230'/nwktime_issue_dd_width: '170'/nwktime_actv_dd_width: '75'/nwktime_page_width: '250'/nwktime_page_height: '297'/nwktime_margin_top: '20'/nwktime_margin_bottom: '20'/nwktime_margin_left: '10'/nwktime_margin_right: '10'/nwktime_line_space: '4'/nwktime_header_logo: logo.jpg/nwktime_restr_max_hour: '1'/nwktime_max_hour_day: '8'/nwktime_min_hour_day: '8'/nwktime_issues_filter_tracker:/n- '0'/nwktime_allow_user_filter_tracker: '1'/nwkexpense_issues_filter_tracker:/n- '0'/nwkexpense_projects:/n- ''/nwktime_use_approval_system: '1'/nwktime_own_approval: '1'/nwktime_submission_ack: ! "I am sure my time tracking is accurate : \r\n* 8 hours for/n  every working days\r\n* 0 for non working days."/nwktime_nonsub_mail_notification: '1'/nwktime_submission_deadline: '1'/nwktime_nonsub_sch_hr: '5'/nwktime_nonsub_sch_min: '0'/nwktime_nonsub_mail_message: ! "Hello,\r\nyou are registered in the Redmine and expected/n  to log your time on the system (8 hours on working days).\r\nYou haven't submitted/n  your timesheet yet.\r\n\r\nWe expect the timesheet to be submitted last day of the/n  week (Friday EOB in europe and Sunday EOB for MENA)\r\n\r\nCould you please make/n  sure to submit your last week timesheet Monday morning the latest?\r\n\r\nIf you/n  need more information, please connect to the Wiki page:\r\n\r\nhttp://192.168.45.106/dokuwiki/doku.php?id=welcome:admin:timetracking\r\n\r\nThank/n  you"/n

As you can see we have : wktime_allow_blank_issue: '1'/n
Thank you,
Wall

**Comment by wallabom** [comment]
After investigating, I can see the issue is when you click "Add Row" on the timesheet.
It is not displaying the blank issue.

As a workaround, here what can be done:

* Add row in the timesheet
* select the project (with default issue selected)
* save the timesheet
* reopen the timesheet and select the issue drop down list for the project
* the blank issue is displayed

This confirms the issue is on the display when you add row on a timesheet 
add time the timesheet with the project and an issue selected, then you click
