### ISSUE TITLE
Internal error with redmine 3.3.1 and wktime 2.9.1

### ISSUE THREAD

**Issue by Korsuario** [dhanasingh/redmine_wktime#107]
Hi,

After installing redmine (3.3.1) and the wktime plugin (2.9.1), I can configure the plugin in the administration tab, however I cannot access the ERPmine tab itself, it presents as internal error.
After checking the error_log in apache I found out that there has been a connection refused in port 80, but I don't understand how can that be, seeing as the port is open:

[Wed Jul 19 17:41:23.868279 2017] [mpm_prefork:notice] [pid 3691] AH00163: Apache/2.4.23 (Unix) OpenSSL/1.0.2j SVN/1.9.4 PHP/5.6.26 Phusion_Passenger/5.0.6 configured -- resuming normal operations
[Wed Jul 19 17:41:23.868331 2017] [core:notice] [pid 3691] AH00094: Command line: '/opt/redmine-3.3.1-0/apache2/bin/httpd.bin -f /opt/redmine-3.3.1-0/apache2/conf/httpd.conf'
/opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:113:in `initialize': Connection refused - connect(2) for "::1" port 80 (Errno::ECONNREFUSED)
        from /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:113:in `new'
        from /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:113:in `rescue in connect'
        from /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:111:in `connect'
        from /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:87:in `socket'
        from /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:91:in `head_request'
        from /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/prespawn:153:in `<main>'
App 3740 stdout:

Any help would be appreciated. Thank you.

**Comment by dhanasingh** [comment]
this could be a compatibility issue
ERPmine 2.9.1 is compatible with Redmine 3.4
ERPmine 2.9 is compatible with Redmine 3.3

Can you please try the right version and see if it works

**Comment by Korsuario** [comment]
Thank you for the help.
I chose to upgrade redmine instead and now it's working.

**Comment by dhanasingh** [comment]
Glad it is working fine, please feel free to rate us at http://www.redmine.org/plugins/wk-time when you get a chance.
