### ISSUE TITLE
redmine cannot start after wktime install

### ISSUE THREAD

**Issue by heidricha** [dhanasingh/redmine_wktime#108]
using official docker version of redmine (:latest)
redmine itserf works as expected.

after installing () wktime plugin, it doesn't appear in redmine's plugin menu, and redmine container will never start again.

install:
```
cd plugins/
git clone https://github.com/dhanasingh/redmine_wktime.git
cd redmine_wktime/
bundle install
rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
```

error msgs preventing the redmine container to start:
redmine_1   | /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler/shared_helpers.rb:110:in `rescue in filesystem_access': There was an error while trying to write to `/usr/src/redmine/Gemfile.lock`. It is likely that you need to grant write permissions for that path. (Bundler::PermissionError)
redmine_1   | 	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler/shared_helpers.rb:108:in `filesystem_access'
redmine_1   | 	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler/definition.rb:306:in `lock'
redmine_1   | 	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:122:in `lock'
redmine_1   | 	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:49:in `setup'
redmine_1   | 	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler.rb:101:in `setup'
redmine_1   | 	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.2/lib/bundler/setup.rb:19:in `<top (required)>'
redmine_1   | 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
redmine_1   | 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
redmine_1   | 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
redmine_1   | 	from /usr/local/bundle/bin/rake:15:in `<main>'

**Comment by dhanasingh** [comment]
Looking at the log, it looks like the /usr/src/redmine/Gemfile.lock file doesn't have the right permission, can you please set the right permission and try again

**Comment by heidricha** [comment]
What shall be the "right permission"? the file is owned by root.root (mod 644) after installation (of redmine) and after the wktime install as well.

Anyway, I have just noticed, that rake returns an error msg:
root@64ac0409e1f3:/usr/src/redmine/plugins/redmine_wktime# rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
(in /usr/src/redmine)
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1+)

**Comment by dhanasingh** [comment]
can you tell us the versions of redmine, erpmine, ruby, rails, OS database etc ?

Also can you try running this command from the redmine folder instead of plugins folder 
rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production

**Comment by heidricha** [comment]
I use the official docker image for redmine. 
---
database is mariadb:latest
---
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  no plugin installed
---
wktime is cloned from github, looks like 2.9.1

root@9ecc340e54eb:/usr/src/redmine# grep Release plugins/redmine_wktime/README.rdoc 
Release Notes for 2.9.1
---
running rake migrate from redmine directory:

root@9ecc340e54eb:/usr/src/redmine# rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1+)
---
root@9ecc340e54eb:/usr/src/redmine# rake --version
rake, version 12.0.0

**Comment by heidricha** [comment]
also tried with redmine 3.3 and wktime v2.9. 

Gemfile.lock access right is still a problem (owned by root while app runs as redmine user), but after correction, the plugin is visible.

rake migration doesn't produce any error

**Comment by dhanasingh** [comment]
We have tested ERPmine 2.9.1 with Redmine 3.4.1, so we are not sure if it would work fine with Redmine 3.4.2 or not, glad you are able to get ERPmine 2.9 working with redline 3.3

**Comment by heidricha** [comment]
redmine 3.4.1 and ERPmine 2.9.1 doesn't work either. behaves the same as 3.4.2/2.9.1

**Comment by pmietlicki** [comment]
Hi, 
I have exactly the same problem. Everything work as expected with redmine 3.3 but not redmine 3.4 (argument error).
Best regards,
Pascal

**Comment by dhanasingh** [comment]
this is the environment we had tested

Environment:
  Redmine version                3.4.1.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.9.1

rake, version 12.0.0

**Comment by dhanasingh** [comment]
Ruby version seems to be different, we have tested under Ruby 2.2 and you have Ruby 2.4

**Comment by heidricha** [comment]
Ruby 2.2 seems to be kinda outdated... any chance to check the installation with 2.4?

I guess people often use the official docker image nowadays, would be very nice to be compatible with that.

**Comment by heidricha** [comment]
Tried to build redmine 3.4.2 with ruby 2.2 (succesfull), but start fails with a similar error message:
redmine_1   | /usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
redmine_1   | Tasks: TOP => db:migrate => environment
redmine_1   | (See full trace by running task with --trace)
redmine_1   | rake aborted!

So it looks like redmine 3.4.2 doesn't even work with ruby 2.2

**Comment by dhanasingh** [comment]
glad to hear ERPmine 2.9.1 and Redmine 3.4.2 works with Ruby 2.2

**Comment by dhanasingh** [comment]
can you try commenting these 2 lines from init.rb and see if it works fine
line 130	base.send(:include)
line 179	base.send(:include)

**Comment by heidricha** [comment]
put comment on lines 130 and 179. 
rake still aborts

```bash
root@4bd653aea483:/usr/src/redmine# rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1+)
/usr/src/redmine/plugins/redmine_wktime/lib/wkpatch.rb:3:in `include'
/usr/src/redmine/plugins/redmine_wktime/lib/wkpatch.rb:3:in `included'
/usr/src/redmine/plugins/redmine_wktime/init.rb:351:in `include'
/usr/src/redmine/plugins/redmine_wktime/init.rb:351:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/src/redmine/lib/redmine/plugin.rb:155:in `block in load'
/usr/src/redmine/lib/redmine/plugin.rb:146:in `each'
/usr/src/redmine/lib/redmine/plugin.rb:146:in `load'
/usr/src/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/usr/src/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:328:in `require'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by heidricha** [comment]
after I removed all similar lines in the code, rake ran well, with no errors at all.
```
	modified:   init.rb
	modified:   lib/report_params.rb
	modified:   lib/wkpatch.rb
```

**Comment by dhanasingh** [comment]
ok, thanks, we will put this change in the next release of ERPmine 3.0

**Comment by Sharpssh** [comment]
Hi, after installation, only two tabs (Time&Expense is HR) are displayed in the ERPmine section, although all the plug-ins are included in the settings. What could be the reason? The configuration is as follows: Environment:
  Redmine version                3.4.4.stable.17180
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.6.0
  redmine_logs                   0.1.1
  redmine_wktime                 3.2

**Comment by dhanasingh** [comment]
Please refer the following issues
#127 
#135
