### ISSUE TITLE
500 Template Error - wrong number of arguments

### ISSUE THREAD

**Issue by DanielBoettner** [dhanasingh/redmine_wktime#109]
Hi there,

I'm trying to get your plugin to run and encounter an issue when accessing **/wktime**.
The log gives me following output.

This runs on 

- Redmine 3.3.0
- ruby 2.1.9-p490 (2016-03-30) [x86_64-linux]
- rails 4.2.6

Please let me know if you can help with the issue.

`Processing by TimeLoggersController#render_menu as */*
  Parameters: {"project_id"=>"110", "issue_id"=>"3051", "_"=>"1501495755399"}
  Current user: username (id=105)
  Rendered plugins/time_logger/app/views/time_loggers/_embed_menu.html.erb (128.8ms)
Completed 200 OK in 140ms (Views: 126.8ms | ActiveRecord: 6.8ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_tab_content.html.erb (0.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_tab_content.html.erb (0.0ms)
  Rendered common/_tabs.html.erb (6.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_date_range.html.erb (5.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_list.html.erb (24.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_te_index.html.erb (145.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/index.html.erb within layouts/base (175.9ms)
Completed 500 Internal Server Error in 913ms (ActiveRecord: 647.3ms)

**ActionView::Template::Error (wrong number of arguments (0 for 1)):**
    42: </table>
    43: </div>
    44: <% end -%>
    45:
    46: <%= context_menu %>
  app/helpers/application_helper.rb:1157:in `context_menu'
  plugins/redmine_wktime/app/views/wktime/_list.html.erb:45:in `_plugins_redmine_wktime_app_views_wktime__list_html_erb__2235404450698953208_70281330258180'
  plugins/redmine_wktime/app/views/wktime/_te_index.html.erb:135:in `_plugins_redmine_wktime_app_views_wktime__te_index_html_erb__4194017294377356601_70281326318800'
  plugins/redmine_wktime/app/views/wktime/index.html.erb:17:in `_plugins_redmine_wktime_app_views_wktime_index_html_erb__1730275012008106545_70281325926020'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:97:in `block (2 levels) in index'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:95:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Comment by karthickmadhiazhagan** [comment]
What version of ERPmine you are using?
ERPmine 2.9.1 is compatible with Redmine 3.4.1.
ERPmine 2.9 is compatible with Redmine 3.3.0.

Thanks,
Karthick

**Comment by DanielBoettner** [comment]
Thanks for the Info. I did not see any information before that 2.9.1 while beeing compatible with 3.4.1 is no longer compatible with 3.3.x

I will change the version.

Maybe you can make this more clear within the readme to prevent others from encountering the same issue. 

Thanks again
