### ISSUE TITLE
LoadError: No such file to load -- ../lib/redmine/Pagination

### ISSUE THREAD

**Issue by box789** [dhanasingh/redmine_wktime#116]
First letter must not be in UPEER case

in redmine directory there is only the file in lower case
 ../lib/redmine/pagination.rb

**Comment by uha666** [comment]
rake aborted!
LoadError: No such file to load -- ../lib/redmine/Pagination
/opt/redmine-3.4.2-3/apps/redmine/htdocs/plugins/redmine_wktime/lib/timelogcontroller_patch.rb:1:in `<top (required)>'
/opt/redmine-3.4.2-3/apps/redmine/htdocs/plugins/redmine_wktime/init.rb:7:in `<top (required)>'
/opt/redmine-3.4.2-3/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine-3.4.2-3/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
/opt/redmine-3.4.2-3/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
/opt/redmine-3.4.2-3/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
/opt/redmine-3.4.2-3/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by karthickmadhiazhagan** [comment]
Could you please remove or comment this first line

> require_dependency  '../lib/redmine/Pagination'
	
 from redmine_wktime\lib\timelogcontroller_patch.rb

and try again.

**Comment by box789** [comment]
I create the symlink with name Pagination.rb to existing file pagination.rb in the same directory - /lib/redmine

After that plugins migration was finished successfully.

**Comment by uha666** [comment]
I just edited the file from redmine_wktime/lib/timelogcontroller_patch.rb and changed:

require_dependency '../lib/redmine/Pagination'

to

require_dependency '../lib/redmine/pagination'

And it now works properly.

Regards

**Comment by box789** [comment]
send pull request https://github.com/dhanasingh/redmine_wktime/pull/117
