### ISSUE TITLE
Mysql2::Error: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Signum** [dhanasingh/redmine_wktime#122]
I try to run the redmine_wktime plugin in combination with MariaDB 10.1.26. Unfortunately the rake migration fails:

```
redmine.intranet:/opt/redmine# rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
Migrating redmine_wktime (ERPmine)...
== 5 CreateWkBilling: migrating ===============================================
-- create_table(:wk_addresses)
   -> 0.0844s
-- create_table(:wk_accounts)
   -> 0.1222s
-- add_index(:wk_accounts, :address_id)
   -> 0.0475s
-- create_table(:wk_account_projects)
   -> 0.0745s
-- add_index(:wk_account_projects, :project_id)
   -> 0.0463s
-- add_index(:wk_account_projects, :account_id)
   -> 0.0584s
-- create_table(:wk_contracts)
   -> 0.0817s
-- add_index(:wk_contracts, :project_id)
   -> 0.0420s
-- add_index(:wk_contracts, :account_id)
   -> 0.0465s
-- create_table(:wk_taxes)
   -> 0.0653s
-- create_table(:wk_acc_project_taxes)
   -> 0.0656s
-- add_index(:wk_acc_project_taxes, :account_project_id)
   -> 0.0466s
-- add_index(:wk_acc_project_taxes, :tax_id)
   -> 0.0542s
-- create_table(:wk_invoices)
   -> 0.0948s
-- add_index(:wk_invoices, :account_id)
   -> 0.0470s
-- add_index(:wk_invoices, :invoice_number, {:unique=>true})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_wk_invoices_on_invoice_number`  ON `wk_invoices` (`invoice_number`) /opt/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'
```

That maximum key size limit seems to be hardcoded in MariaDB and certain (newer) versions of MySQL. Some say that using an UTF8 encoding might help to save bytes. What would be the right way to fix this?

**Comment by dhanasingh** [comment]
We have not seen this error before 
is it saying the key name `index_wk_invoices_on_invoice_number` is too long ?
I think that is formed automatically by rails using the table and key name
what version of ruby are you using and what is the platform ?

**Comment by Signum** [comment]
IMHO the error points to the data size of the key - not the name of it. So wktime is storing data in that key field that exceeds 767 bytes which seems to be the hard limit of keys in newer MySQL versions. Some say that the limit was higher in earlier versions. Some say that it might be a matter of 4-byte Unicode encoding. I don't know to be honest.

Environment:
  Debian Jessie 9.0
  Redmine version                3.4.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_timesheet_plugin       0.7.0
  redmine_wktime                 3.0.1
  timelog_timer                  2.0.0

Database is MariaDB 10.1.26

**Comment by dhanasingh** [comment]
we are not sure either.  since you are installing for the first time, you won't have any data for those fields.  it is only creating the invoice table end an unique index on the invoice number field, which is failing.
how would you change it to UTF-8 encoding ? during the db creation ?

**Comment by Signum** [comment]
Not sure about the UTF encoding. But IMHO the installation and db migration should work with a default MariaDB installation. Did you try with a fresh MariaDB installation and not get the error?

**Comment by dhanasingh** [comment]
no, we have tested in mysql, postgres and SQL Server, not mariadb

**Comment by n002213f** [comment]
Found this issue while search for the same error.

I had the same installing Redmine. I found a working solution here; http://www.redmine.org/boards/2/topics/54308

Recreate the database; `CREATE DATABASE redmine DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;`

Hope its helps.

**Comment by DannasCornell** [comment]
You can update the value

ALTER DATABASE redmine COLLATE = 'utf8_general_ci';

**Comment by aneshodza** [comment]
If you're here at some point in the future because SemaphoreCI or some other CI is causing issues, maybe [this helps](https://github.com/aneshodza/redmine-postgres-database-yml)
