### ISSUE TITLE
Failure when importing attendance

### ISSUE THREAD

**Issue by man2004** [dhanasingh/redmine_wktime#123]
Hi,

When I tried to import attendance, it reported "Import failed: undefined method `+' for nil:NilClass". This happened with your Test / Sandbox environment https://demo1.adhisoftware.co.in as well

Please help

**Comment by dhanasingh** [comment]
What version of redline and erpmine are you using ?
Did you configure the attendance  import section of the plugin ?
can you post a data file (sample) here ?

**Comment by man2004** [comment]
Hi,

I am using Redmine 3.3.2 and ERPmine 2.9. I tried to configure the attendance import section but no help. As said, I also tried with your demo site and got same result.

My data file simple. To try in your demo site for the user ID 7 (pm1),

7 10:00

Can you instruct me how to work this in your demo site?  Then I think I will know how to do with my own installation.

**Comment by dhanasingh** [comment]
did you configure the 'fields in file' under the plugin configuration ?
go to Administration -> plugins -> ERPmine -> configure -> Attendance
you will have to select userid and start time  in the fields in file list box, userid should be first in list

**Comment by man2004** [comment]
Thanks. I have figured out why not work. By default the list box has a blank entry at the top. I removed it and then it is OK now.
