### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by tejas1493** [dhanasingh/redmine_wktime#124]
Hi!
I am facing some issue while installing this plugin and please find below the details

## System Details:
> Linux tredence 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

And i followed your `README.md` file to install.
Steps i followed to install
- Cloned repository
- executed the following command inside `plugin` directory
   > sudo bundle install

   >  sudo rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production

after this i am getting following error

    tejas@tejas:/usr/share/redmine/plugins/redmine_wktime$ sudo rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
    (in /usr/share/redmine)
    rake aborted!
    Bundler::GemRequireError: There was an error while trying to load the gem 'redmine_extensions'.
    Gem Load Error is: undefined method `require_dependency' for main:Object
    Backtrace for gem load error is:
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions/redmine_patches/patches.rb:3:in `block in <top (required)>'
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions/redmine_patches/patches.rb:2:in `each'
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions/redmine_patches/patches.rb:2:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions/engine.rb:2:in `require'
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions/engine.rb:2:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions.rb:1:in `require'
    /var/lib/gems/1.9.1/gems/redmine_extensions-0.1.07/lib/redmine_extensions.rb:1:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
    /usr/share/redmine/config/application.rb:5:in `<top (required)>'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/share/redmine/Rakefile:5:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:688:in `raw_load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:97:in `block in load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:96:in `load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:80:in `block in run'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
    /usr/local/bin/rake:23:in `load'
    /usr/local/bin/rake:23:in `<main>'
    Bundler Error Backtrace:
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:86:in `rescue in block (2 levels) in require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
    /var/lib/gems/1.9.1/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
    /usr/share/redmine/config/application.rb:5:in `<top (required)>'
    /usr/share/redmine/Rakefile:5:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
    (See full trace by running task with --trace)

# I am using `Redmine-3.0.4`

**Comment by dhanasingh** [comment]
Can you try the below command From /usr/share/redmine folder ?

 sudo rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production

**Comment by tejas1493** [comment]
@dhanasingh i tried the command in `/usr/share/redmine` folder. And the same command i executed.

**Comment by dhanasingh** [comment]
so it is still not working ?

**Comment by dhanasingh** [comment]
and what version of ermine are you using ?

**Comment by tejas1493** [comment]
Below is the information:

> Environment:
>   Redmine version                3.4.3.stable
>   Ruby version                   2.1.9-p494 (2017-09-14) [x86_64-linux-gnu]
>   Rails version                  4.2.8
>   Environment                    production
>   Database adapter               Mysql2

**Comment by tejas1493** [comment]
And can you tell me where i have to enable the below one. I mean in which file i am using [this link](http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_25x_on_Ubuntu_1404_with_Apache2_Phusion_Passenger_MySQL_and_Subversion) for installation

`For rufus-scheduler to work , the rails application should be up all the time. If an apache passenger module is used then make sure the following settings are made`

> PassengerMinInstances 1
> RailsAppSpawnerIdleTime 0
> PassengerPreStart http://<rails-app-url>/

**Comment by dhanasingh** [comment]
it is failing on the remind_extensions gem
do you have multiple versions of ruby installed on your machine ?
the gems seems to be of version 1.9.1 when migrating the plugin

**Comment by dhanasingh** [comment]
if you are using apache and passenger, the passenger config would go into the httpd.conf
