### ISSUE TITLE
ActionView::Template::Error (wrong number of arguments (given 0, expected 1)):

### ISSUE THREAD

**Issue by froy001** [dhanasingh/redmine_wktime#129]
When upgrading from v2.8 to v3.1 I get the error below when clicking the ERPmine link from the nav menu. The plugin configuration works fine. 

The app info:
Environment:
  Redmine version                3.3.5.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux-musl]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.8.6
  Filesystem                     
  GitRemote                      2.8.6
Redmine plugins:
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_contacts               4.1.1
  redmine_contacts_helpdesk      3.0.9
  redmine_contacts_invoices      4.1.6
  redmine_crm_mailchimp          1.0.2
  redmine_finance                2.1.3
  redmine_git_remote             0.0.1
  redmine_messenger              1.0.1
  redmine_people                 1.3.2
  redmine_products               2.0.4
  redmine_wktime                 3.1

```
ActionView::Template::Error (wrong number of arguments (given 0, expected 1)):
    42: </table>
    43: </div>
    44: <% end -%>
    45: 
    46: <%= context_menu %>
  app/helpers/application_helper.rb:1158:in `context_menu'
  plugins/redmine_wktime/app/views/wktime/_list.html.erb:45:in `_plugins_redmine_wktime_app_views_wktime__list_html_erb__1764417930960864538_47424397082880'
  plugins/redmine_wktime/app/views/wktime/_te_index.html.erb:135:in `_plugins_redmine_wktime_app_views_wktime__te_index_html_erb__3073593013925537023_47424400937040'
  plugins/redmine_wktime/app/views/wktime/index.html.erb:17:in `_plugins_redmine_wktime_app_views_wktime_index_html_erb__2432851635814798013_47424401100700'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:97:in `block (2 levels) in index'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:95:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by dhanasingh** [comment]
this could be a version compatibility issue.
ERPmine 3.1 is compatible with Redmine 3.4
ERPmine 2.9 is compatible with Redmine 3.3

Can you please get the right version and check

**Comment by froy001** [comment]
Thanks for the clarification. It does work with Redmine 3.3 and ERPmine 2.9
