### ISSUE TITLE
Worktime header

### ISSUE THREAD

**Issue by projectplant** [dhanasingh/redmine_wktime#13]
Hi,

We are using your Redmine Plugin "Time & Expenses" with Redmine 3.01. We configured the "worktime header", but we are really wondering, if it is not stored/loaded?

If we enter a value, next time we open the sheet, the value is gone. Is there any functionality behind the fields, or they are just for fun?

Thanks.
Marc

**Comment by dhanasingh** [comment]
No, the work time header info is not stored, it is for the user to enter when they start and end work on a day.  And you will have to enter every time you come to the edit page

**Comment by suganya-thulasiraman** [comment]
We have a new feature 'Enable clock in/ clock out', with that we are saving clock in and clock out time.

**Comment by projectplant** [comment]
Well, I know - in your current release the data is stored in table wk_attendances ... we added a script (curl and MySQL import into Redmine schema) and a stored procedure to fill in data from our attendance recorder. If anyone is interested, we like to share ... our attendance recorder is a SafeScan TA-955.

The issue can be closed.

**Comment by suganya-thulasiraman** [comment]
Could you please share your script and stored procedure with us

**Comment by mmiat** [comment]
+1

**Comment by karthickmadhiazhagan** [comment]
Hi Marc,
Can you please share your script and stored procedure with us. There are some other users also request this feature.

Thanks,
Karthick
