### ISSUE TITLE
Issue Checklist Plugin crashed

### ISSUE THREAD

**Issue by sruttloff** [dhanasingh/redmine_wktime#133]
Open of issue checklist configuration crashes with 500 Error.
In the log:

NoMethodError (undefined method `merge!' for "":String):
  plugins/redmine_wktime/init.rb:182:in `plugin'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Redmine is 3.3.2
ERPMine 3.1
Checklist 3.1.10 light

**Comment by dhanasingh** [comment]
ERPmine 2.9 is compatible with Redmine 3.3.x
ERPmine 3.1 is compatible with Remdine 3.4.x

Can you please get the right versions and check again

**Comment by sruttloff** [comment]
Same problem with version 2.9 of your plugin.
But it happens only in combination with Checklist plugin, when I try to open Checklist plugin configuration page.

If I remove your plugin, I can open the Checklist configuration page. There must be something dependig.?

**Comment by dhanasingh** [comment]
This is fixed in ERPmine 3.2, can you please check
