### ISSUE TITLE
Plugin index not working

### ISSUE THREAD

**Issue by mehdawi77** [dhanasingh/redmine_wktime#134]
Dear Sir,

After following installation steps; except that I am testing on Redmine 3.2, when trying to access the wktime/index the following error:

Error log
        /var/www/redmine/app/helpers/application_helper.rb:1128:in `context_menu'
/var/www/redmine/plugins/redmine_wktime/app/views/wktime/_list.html.erb:45:in `_b196f641675f4f0240b702014b1ba4b0'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:25:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
/var/www/redmine/plugins/redmine_wktime/app/views/wktime/_te_index.html.erb:135:in `_f43f86bd1acdcfd9f195a34cb508d918'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:25:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
/var/www/redmine/plugins/redmine_wktime/app/views/wktime/index.html.erb:17:in `_ac58e6bbe8ff4a3ef5bdb988f9615188'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:46:in `render_template'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:27:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:100:in `_render_template'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/rendering.rb:25:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:16:in `render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
/var/www/redmine/plugins/redmine_wktime/app/controllers/wktime_controller.rb:97:in `block (2 levels) in index'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
/var/www/redmine/plugins/redmine_wktime/app/controllers/wktime_controller.rb:95:in `index'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/www/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/www/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

Kindly your help.

Thanks.

**Comment by dhanasingh** [comment]
what is the version of erpmine ?
ERPmine 2.2 is compatible with Redmine 3.2
ERPmine 3.1 is compatible with Redmine 3.4

**Comment by mehdawi77** [comment]
ERPmine 3.1 on redmine 3.2; is this wrong?

**Comment by dhanasingh** [comment]
ERPmine 3.1 is not compatible with Redmine 3.2, please get the right versions and try again, thanks

**Comment by mehdawi77** [comment]
Thanks for your support.
