### ISSUE TITLE
click "ERPmine" in top menu, only  "Time & Expense" and "HR" display，no others, no "setting"

### ISSUE THREAD

**Issue by gisok** [dhanasingh/redmine_wktime#135]
click "ERPmine" in top menu, only  "Time & Expense" and "HR" display，no others, no "setting"?
HELP!
## Environment:

  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL

**Comment by dhanasingh** [comment]
Please check if the logged in user is part of the following groups
T&E Admin - for settings tab
Billing Admin
Purchasing Admin
Accounting Admin

These can be setup from Administration -> plugins -> ERPmine -> configure
and the setup the admin groups for each module

**Comment by gisok** [comment]
problem solved！
Excitement！
thanks！
