### ISSUE TITLE
Submit button for timesheets doesn't show up

### ISSUE THREAD

**Issue by Mutniks** [dhanasingh/redmine_wktime#138]
Hi there, great plugin. Unfortunately, the submit button doesn't show up for me, even though I activated the 'use approval system' check box in the plugin settings, and I restarted redmine. I only see "save" and "save and continue" buttons. I'm logged in as admin. I also activated all permissions for all roles of the plugin for admins in the permission settings of redmine. Using redmine_wktime 3.2 and Redmine version                3.4.4.stable.

**Comment by dhanasingh** [comment]
This seems to be a bug, we are looking into it, should have a fix soon

**Comment by dhanasingh** [comment]
this is fixed in ERPmine 3.2.1, can you please check
