### ISSUE TITLE
 Add to timesheet form username of user that changed

### ISSUE THREAD

**Issue by dima21m** [dhanasingh/redmine_wktime#14]
Hello
Could you Add to timesheet form username of user that changed the current status near of timesheet status?
In data base this information store in:
Table - wktimes
Field - statusupdater_ID

**Comment by suganya-thulasiraman** [comment]
Ok, we will put this in future release.

**Comment by suganya-thulasiraman** [comment]
We have added a 'Modified by' column in list page.
