### ISSUE TITLE
Invoice from Project/Tasks Spent Time

### ISSUE THREAD

**Issue by Nevyn75** [dhanasingh/redmine_wktime#141]
Hi.

Is it possible to generate automatically an entry into an invoice for a Customer, by taking the developers spent time on specific tasks or on entire project in a selected time period?

Thank you and best regards.

**Comment by dhanasingh** [comment]
not sure how much billing module setup you have, these are the things you will have to setup;
1) enter the customer as a contact or account in the CRM module.  Accounts are companies, contacts are individuals
2) Setup a billable project for that account / contact user billing module
4) if it is a hourly billing, you will have to setup the hourly rate and currency
    The rate can be setup at user or issue or project. need to create custom fields in Project / issue for the rate and currency, need to set that up in plugin settings
5) need to create a custom field in spent time and configure that as the time entry billing id in the plugin setting
6) if you are starting off of a existing redmine and wants to use billing module from a certain date, set the 'Generate Invoice From field' in the plugin setting

Once these are setup, you can select the period and generate invoice, please note if there are any unmilled items in the prior period before the selected period, it will include that also.  it uses the time entry billing id field to determine whether a time entry is billed or not.

hope this helps, let me know if you have any questions.

**Comment by Nevyn75** [comment]
Hi and thanks for support.

I have set an account and a billable project for it.
Inside the project there's some spent time for a user with an attached rate.

This is my situation in settings:

![image](https://user-images.githubusercontent.com/443001/37825991-2018e8ca-2e92-11e8-86ef-7be5fd8bf71c.png)

It is not clear to me (also after reading the user manual), how to generate the invoice for example for the current month.

Thank you and best regards.

**Comment by dhanasingh** [comment]
on the invoice list page, there is a 'generate invoice' link, 
there is also a 'unbilled invoice' link, which will not generate, but show only a preview of the unmilled.
