### ISSUE TITLE
Error 500 after Install: "ActionView::Template::Error (Missing partial wkbase/_base_header)"

### ISSUE THREAD

**Issue by Matzenino** [dhanasingh/redmine_wktime#151]
Hi! 

I'm trying out your plugin for the first time but cannot seem to get it to work.

On my Redmine 3.4.6 installation the following error occurs:

```
ActionView::Template::Error (Missing partial wkbase/_base_header with {:locale=>[:de, :en], :formats=> [:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :haml, :rsb]}. 
Searched in: 
  * "/var/www/redmine/plugins/redhopper/app/views" 
 * "/var/www/redmine/app/views" 
 ): 
```

Full Log is in the following file:
[auszug_production_log.txt](https://github.com/dhanasingh/redmine_wktime/files/2292987/auszug_production_log.txt)

**ServerInfo:** 
Redmine version          3.4.6.stable
Ruby version                2.3.3-p222 (2016-11-21) [x86_64-linux]
Rails version                 4.2.8
Environment                production
Database adapter        Mysql2

The only other Plugin that is currently installed is Redhopper, but even without it the error still occurs.

Any Idea what's missing?

**Comment by dhanasingh** [comment]
it is actually complaining on the redhopper plugin, are you sure you completely uninstalled the redhopper plugin ?

**Comment by dhanasingh** [comment]
are you still having issues ?

**Comment by AbdullahMuhammad** [comment]
@dhanasingh I am having same issue

**Comment by dhanasingh** [comment]
can you please provide details

**Comment by AbdullahMuhammad** [comment]
@dhanasingh What details do you want ?

**Comment by dhanasingh** [comment]
the error you are getting, the page on which you are getting the error, the extract from the log file

**Comment by AbdullahMuhammad** [comment]
@dhanasingh I will provide you the detail today.

**Comment by deepankargaur** [comment]
@dhanasingh I tried installing your plugin in bitnami redmine and I am getting similar issue with it. My production log is below,

Started GET "/redmine/" for fe80::8ded:307a:eda7:d19a at 2018-11-16 18:31:06 +0530
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (7.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 500 Internal Server Error in 237ms (ActiveRecord: 38.3ms)

ActionView::Template::Error (Missing partial wkbase/_base_header with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "T:/Redmine/apps/redmine/htdocs/plugins/under_construction/app/views"
  * "T:/Redmine/apps/redmine/htdocs/plugins/scrum/app/views"
  * "T:/Redmine/apps/redmine/htdocs/plugins/redmine_monitoring_controlling/app/views"
  * "T:/Redmine/apps/redmine/htdocs/plugins/due_date_reminder/app/views"
  * "T:/Redmine/apps/redmine/htdocs/plugins/a_common_libs/app/views"
  * "T:/Redmine/apps/redmine/htdocs/app/views"
):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__259443227_52304652'
  app/controllers/application_controller.rb:491:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:489:in `render_error'
  app/controllers/application_controller.rb:477:in `render_404'
  app/controllers/application_controller.rb:501:in `missing_template'

**Comment by deepankargaur** [comment]
Hey I think I found the issue and the solution.
Default name of the plugin folder is "**redmine_wktime-master**"
It shall be renamed to "**redmine_wktime**" before performing rake of the database.

@Matzenino @AbdullahMuhammad @dhanasingh 

Cheers
DG

**Comment by AbdullahMuhammad** [comment]
@deepankargaur If you are looking for budgeting and cost calculations of a project please also explore
https://www.openproject.org/
