### ISSUE TITLE
ActionView::Template::Error (undefined method `name' for nil:NilClass):

### ISSUE THREAD

**Issue by PawelSkrzypkowski** [dhanasingh/redmine_wktime#154]
I have an error when I select in issue in field Additional assignee group name. After saving or trying to view this issue such error appears in log file:
`ActionView::Template::Error (undefined method 'name' for nil:NilClass):`

ServerInfo:
Redmine version 3.4.6
Ruby version 2.4.1
Rails version 4.2.8
Environment production
Database adapter Mysql2
Full error is in file:
[error.txt](https://github.com/dhanasingh/redmine_wktime/files/2441933/error.txt)

PS: In addition, I would like to know if it is possible to delete this field. If there is no such option, I would suggest adding, because for example in my company it is not used.

**Comment by dhanasingh** [comment]
Thank you, this problem is fixed in erpmine 3.3.3.
Currently, it is not possible to hide this field now, we will take this as a feature request for future.
