### ISSUE TITLE
SVG Graph Gem Dependency

### ISSUE THREAD

**Issue by cfis** [dhanasingh/redmine_wktime#163]
Get the traceback below using Redmine 4 with the dev branch.

Easy solution, add to Gemfile:

gem "svg-graph", "~2.1.3"

-------------------------------------

/usr/lib64/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': No such file to load -- SVG/Graph/Bar.rb (LoadError)
        from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /srv/redmine/plugins/redmine_wktime/app/controllers/wkdashboard_controller.rb:2:in `<class:WkdashboardController>'
        from /srv/redmine/plugins/redmine_wktime/app/controllers/wkdashboard_controller.rb:1:in `<top (required)>'

**Comment by arunkumart1995** [comment]
We have commented the SVG Graph on Dev-Branch.

**Comment by cfis** [comment]
It seemed to work fine as long as the gem was required.

**Comment by dhanasingh** [comment]
thanks for the info
we have included the gem in erpmine 3.4
erpmine 3.4 is compatible with Redmine 4.0
