### ISSUE TITLE
Project can't be selected when making quote or purchase order

### ISSUE THREAD

**Issue by anderwm** [dhanasingh/redmine_wktime#166]
Although you can filter by project, there doesn't seem to be a way to actually add the project to quote/purchase order when creating them. Am I missing something?

**Comment by dhanasingh** [comment]
actually it is a procure to pay process, there may not be a project involved in this I think.
We can have a project associated with the quote to cash process.  There is a quote entity yet in the CRM module, we plan to add that later.  But for now, you cancreate a lead in CRM, convert them to Account and add a billable project for it.  does this help ?

**Comment by anderwm** [comment]
I will experiment with it, thanks for your reply.
