### ISSUE TITLE
Additional Details removal

### ISSUE THREAD

**Issue by BRUTEF0RCE** [dhanasingh/redmine_wktime#169]
Is there any way to remove the additional details / additional assignee section of the issue?

![image](https://user-images.githubusercontent.com/6563540/51295451-a7818800-19e5-11e9-8149-cb6108a6321d.png)

What is it used for? We do not use it and it crowds the issue UI without necessity.

Thanks

**Comment by dhanasingh** [comment]
There is a new configuration 'No Additional Details for Issues' in version 3.5, when set, will hide the additional details section, please take a look

**Comment by BRUTEF0RCE** [comment]
Is this version compatible with Redmine 3.4.x? Or only 4.x?

**Comment by dhanasingh** [comment]
yes, ERPmine 3.5 is compatible only with Redmine 4.0

**Comment by BRUTEF0RCE** [comment]
How far back do I have to go to avoid the additional details and a version compatible with 3.4.x?

**Comment by dhanasingh** [comment]
it got introduced in ERPmine 3.3, you can use ERPmine 3.2.1
