### ISSUE TITLE
After installing ERPmine 3.4 on brand new (Bitnami) Redmine 4.0.1, Redmine doesn't start anymore

### ISSUE THREAD

**Issue by andrea-ligios** [dhanasingh/redmine_wktime#174]
Hi, I've installed a Bitnami Redmine Stack VM, with Redmine 4.0.1.

This is a brand new installation with default data inside, and I've already performed many attempts at installing the plugin.

I've downloaded ERPMine version 3.4, which should work with Redmine 4.0.x, unzipped into 

    /opt/bitnami/apps/redmine/htdocs/plugins 

Then I've run from that folder:

    bundle install

Which ended succesfully :

> ``` 
> Fetching gem metadata from http://rubygems.org/..............
> Fetching version metadata from http://rubygems.org/..
> Resolving dependencies...
> Installing rufus-scheduler 3.2.0
> Installing svg-graph 2.1.3
> Using bundler 1.14.6
> Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
> Use `bundle show [gemname]` to see where a bundled gem is installed.
> ```

Finally, I've moved from the plugin folder to the htdocs folder, and run the db migration command: 

    cd /opt/bitnami/apps/redmine/htdocs
    bin/rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production

and got the following output (which seems fine to me, apart from a warning for the log file not being writable, which is odd since it's already 664 to daemon:daemon):

> ```
> Rails Error: Unable to access log file. 
> Please ensure that /opt/bitnami/apps/redmine/htdocs/log/production.log exists and is writable 
> (ie, make it writable for user and group: chmod 0664 /opt/bitnami/apps/redmine/htdocs/log/production.log).
> The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
> Creating scope :system. Overwriting existing method Enumeration.system.
> Creating scope :sorted. Overwriting existing method Group.sorted.
> Creating scope :sorted. Overwriting existing method User.sorted.
> Migrating to CreateWktimes (1)
> == 1 CreateWktimes: migrating =================================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wktimes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0137s
> -- add_index(:wktimes, :user_id)
>    -> 0.0146s
> -- add_index(:wktimes, :begin_date)
>    -> 0.0167s
> == 1 CreateWktimes: migrated (0.0494s) ========================================
> 
> Migrating to CreateWkExpenseEntries (2)
> == 2 CreateWkExpenseEntries: migrating ========================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_expense_entries, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0395s
> -- add_index(:wk_expense_entries, [:project_id], {:name=>:wk_expense_entries_project_id})
>    -> 0.0246s
> -- add_index(:wk_expense_entries, [:issue_id], {:name=>:wk_expense_entries_issue_id})
>    -> 0.0130s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wkexpenses, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0107s
> -- add_index(:wkexpenses, :user_id)
>    -> 0.0099s
> -- add_index(:wkexpenses, :begin_date)
>    -> 0.0104s
> == 2 CreateWkExpenseEntries: migrated (0.1133s) ===============================
> 
> Migrating to CreateWkAttendances (3)
> == 3 CreateWkAttendances: migrating ===========================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_attendances, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0109s
> -- add_index(:wk_attendances, :user_id)
>    -> 0.0105s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_user_leaves, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0122s
> -- add_index(:wk_user_leaves, :user_id)
>    -> 0.0128s
> == 3 CreateWkAttendances: migrated (0.0504s) ==================================
> 
> Migrating to CreateWkSalaryComponents (4)
> == 4 CreateWkSalaryComponents: migrating ======================================
> -- adapter_name()
>    -> 0.0001s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_salary_components, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0119s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_user_salary_components, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0127s
> -- add_index(:wk_user_salary_components, :user_id)
>    -> 0.0097s
> -- add_index(:wk_user_salary_components, :salary_component_id)
>    -> 0.0108s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_salaries, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0106s
> -- add_index(:wk_salaries, :user_id)
>    -> 0.0098s
> -- add_index(:wk_salaries, :salary_component_id)
>    -> 0.0111s
> -- add_index(:wk_salaries, :salary_date)
>    -> 0.0087s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_h_user_salary_components, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0106s
> == 4 CreateWkSalaryComponents: migrated (0.1054s) =============================
> 
> Migrating to CreateWkBilling (5)
> == 5 CreateWkBilling: migrating ===============================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_addresses, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0126s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_accounts, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0376s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_account_projects, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0128s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_contracts, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0098s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_taxes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0096s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_acc_project_taxes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0143s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_invoices, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0110s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_invoice_items, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0109s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_billing_schedules, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0098s
> -- add_index(:wk_accounts, :address_id)
>    -> 0.0149s
> -- add_index(:wk_account_projects, :project_id)
>    -> 0.0097s
> -- add_index(:wk_account_projects, :account_id)
>    -> 0.0108s
> -- add_index(:wk_contracts, :project_id)
>    -> 0.0088s
> -- add_index(:wk_contracts, :account_id)
>    -> 0.0186s
> -- add_index(:wk_acc_project_taxes, :account_project_id)
>    -> 0.0075s
> -- add_index(:wk_acc_project_taxes, :tax_id)
>    -> 0.0147s
> -- add_index(:wk_invoices, :account_id)
>    -> 0.0139s
> -- add_index(:wk_invoices, :invoice_number, {:unique=>true})
>    -> 0.0161s
> -- add_index(:wk_invoice_items, :invoice_id)
>    -> 0.0115s
> -- add_index(:wk_invoice_items, :project_id)
>    -> 0.0113s
> -- add_index(:wk_billing_schedules, :account_project_id)
>    -> 0.0110s
> -- add_index(:wk_billing_schedules, :invoice_id)
>    -> 0.0090s
> == 5 CreateWkBilling: migrated (0.3124s) ======================================
> 
> Migrating to CreateWkAccounting (6)
> == 6 CreateWkAccounting: migrating ============================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_ledgers, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0300s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_gl_transactions, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0125s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_gl_transaction_details, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0377s
> -- add_index(:wk_gl_transaction_details, :ledger_id)
>    -> 0.0121s
> -- add_index(:wk_gl_transaction_details, :gl_transaction_id)
>    -> 0.0092s
> -- add_reference(:wk_salary_components, :ledger, {:type=>:integer, :class=>"wk_ledgers", :null=>true, :index=>true})
>    -> 0.0510s
> -- add_reference(:wk_invoices, :gl_transaction, {:type=>:integer, :class=>"wk_gl_transactions", :null=>true, :index=>true})
>    -> 0.0512s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_gl_salaries, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0109s
> == 6 CreateWkAccounting: migrated (0.2842s) ===================================
> 
> Migrating to CreateWkCrm (7)
> == 7 CreateWkCrm: migrating ===================================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_crm_enumerations, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0106s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_crm_activities, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0156s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_crm_contacts, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0126s
> -- add_index(:wk_crm_contacts, :address_id)
>    -> 0.0122s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0001s
> -- create_table(:wk_leads, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0105s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_opportunities, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0153s
> -- add_column(:wk_addresses, :department, :string, {})
>    -> 0.0189s
> -- add_column(:wk_addresses, :website, :string, {})
>    -> 0.0512s
> -- add_reference(:wk_accounts, :activity, {:type=>:integer, :class=>"wk_crm_activites", :null=>true, :index=>true})
>    -> 0.0675s
> -- add_column(:wk_accounts, :account_category, :string, {})
>    -> 0.0729s
> -- add_column(:wk_accounts, :industry, :string, {})
>    -> 0.0258s
> -- add_column(:wk_accounts, :annual_revenue, :float, {})
>    -> 0.0207s
> -- add_column(:wk_accounts, :description, :string, {})
>    -> 0.0226s
> -- add_reference(:wk_accounts, :assigned_user, {:type=>:integer, :class=>"User", :index=>false})
>    -> 0.0252s
> -- add_reference(:wk_accounts, :created_by_user, {:type=>:integer, :class=>"User", :index=>false})
>    -> 0.0241s
> -- add_reference(:wk_accounts, :updated_by_user, {:type=>:integer, :class=>"User", :index=>false})
>    -> 0.0234s
> == 7 CreateWkCrm: migrated (0.6261s) ==========================================
> 
> Migrating to CreateWkPayment (8)
> == 8 CreateWkPayment: migrating ===============================================
> -- add_reference(:wk_invoices, :parent, {:type=>:integer, :polymorphic=>true, :index=>true})
>    -> 0.0686s
> -- add_reference(:wk_contracts, :parent, {:type=>:integer, :polymorphic=>true, :index=>true})
>    -> 0.0749s
> -- add_reference(:wk_account_projects, :parent, {:type=>:integer, :polymorphic=>true, :index=>true})
>    -> 0.0511s
> -- execute("\t\t\t  UPDATE wk_invoices set parent_id = account_id, parent_type = 'WkAccount' ;\n")
>    -> 0.0008s
> -- execute("\t\t\t  UPDATE wk_contracts set parent_id = account_id, parent_type = 'WkAccount' ;\n")
>    -> 0.0005s
> -- execute("\t\t\t  UPDATE wk_account_projects set parent_id = account_id, parent_type = 'WkAccount' ;\n")
>    -> 0.0005s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_payments, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0132s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_payment_items, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0161s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_ex_currency_rates, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0107s
> -- add_reference(:wk_invoice_items, :credit_invoice, {:type=>:integer, :class=>"wk_invoices", :index=>false})
>    -> 0.0217s
> -- add_reference(:wk_invoice_items, :credit_payment_item, {:type=>:integer, :class=>"wk_payment_items", :index=>false})
>    -> 0.0222s
> -- remove_reference(:wk_invoices, :account, {:class=>"wk_accounts", :null=>true})
>    -> 0.0292s
> -- remove_reference(:wk_contracts, :account, {:class=>"wk_accounts", :null=>true})
>    -> 0.0417s
> -- remove_reference(:wk_account_projects, :account, {:class=>"wk_accounts", :null=>true})
>    -> 0.0258s
> == 8 CreateWkPayment: migrated (0.3814s) ======================================
> 
> Migrating to CreateWkPurchase (9)
> == 9 CreateWkPurchase: migrating ==============================================
> -- add_column(:wk_invoices, :invoice_type, :string, {:limit=>5, :default=>"I"})
>    -> 0.0205s
> -- add_column(:wk_crm_contacts, :contact_type, :string, {:limit=>5, :default=>"C"})
>    -> 0.0188s
> -- add_column(:wk_invoices, :invoice_num_key, :integer, {})
>    -> 0.0247s
> -- add_reference(:wk_payments, :gl_transaction, {:type=>:integer, :class=>"wk_gl_transactions", :index=>false})
>    -> 0.0224s
> -- remove_reference(:wk_payment_items, :gl_transaction, {:class=>"wk_gl_transactions", :null=>true})
>    -> 0.0222s
> -- execute("\t\t\t\t  UPDATE wk_invoices set invoice_num_key = id;\n")
>    -> 0.0007s
> -- index_name(:wk_invoices, {:column=>:invoice_number})
>    -> 0.0000s
> -- index_name_exists?(:wk_invoices, "index_wk_invoices_on_invoice_number")
>    -> 0.0011s
> -- remove_index(:wk_invoices, {:column=>:invoice_number, :name=>"index_wk_invoices_on_invoice_number"})
>    -> 0.0081s
> -- add_index(:wk_invoices, :invoice_number, {:unique=>false})
>    -> 0.0525s
> -- adapter_name()
>    -> 0.0000s
> -- change_column(:wk_invoice_items, :project_id, :integer, {:null=>true})
>    -> 0.0621s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_rfqs, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0330s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_rfq_quotes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0187s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_po_quotes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0263s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_po_supplier_invoices, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0400s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_te_locks, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0116s
> == 9 CreateWkPurchase: migrated (0.3675s) =====================================
> 
> Migrating to CreateWkInventory (10)
> == 10 CreateWkInventory: migrating ============================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_product_categories, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0108s
> -- add_reference(:wk_product_categories, :parent, {:type=>:integer, :class=>"wk_product_categories", :index=>true})
>    -> 0.0322s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_mesure_units, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0095s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_brands, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0103s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_product_attributes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0180s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_attribute_groups, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0090s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_products, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0189s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_product_models, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0169s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_brand_products, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0156s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_product_taxes, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0470s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_shipments, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0162s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_locations, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0153s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_product_items, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0189s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_inventory_items, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0284s
> -- add_reference(:wk_inventory_items, :parent, {:type=>:integer, :class=>"wk_inventory_items", :index=>true})
>    -> 0.0406s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_material_entries, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0186s
> -- add_index(:wk_material_entries, [:project_id], {:name=>:wk_material_entries_project_id})
>    -> 0.0133s
> -- add_index(:wk_material_entries, [:issue_id], {:name=>:wk_material_entries_issue_id})
>    -> 0.0107s
> -- add_reference(:wk_invoice_items, :product, {:type=>:integer, :class=>"wk_products", :index=>true})
>    -> 0.0349s
> == 10 CreateWkInventory: migrated (0.3951s) ===================================
> 
> Migrating to CreateWkAssetManagement (11)
> == 11 CreateWkAssetManagement: migrating ======================================
> -- add_column(:wk_products, :depreciation_rate, :float, {})
>    -> 0.0232s
> -- add_reference(:wk_products, :ledger, {:type=>:integer, :class=>"wk_ledgers", :null=>true, :index=>true})
>    -> 0.0336s
> -- add_column(:wk_inventory_items, :is_loggable, :boolean, {:default=>true})
>    -> 0.0300s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_asset_properties, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0308s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_asset_depreciations, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0144s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_permissions, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0128s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_group_permissions, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0138s
> -- execute("\t\t\t\t\tINSERT INTO wk_permissions(id, name, short_name, created_at, updated_at) VALUES (1, 'INVENTORY_VIEW', 'V_INV', current_timestamp,                                                                                       current_timestamp);\n")
>    -> 0.0018s
> -- execute("\t\t\t\t\tINSERT INTO wk_permissions(id, name, short_name, created_at, updated_at) VALUES (2, 'INVENTORY_DELETE', 'D_INV', current_timestam                                                                                      p, current_timestamp);\n")
>    -> 0.0009s
> == 11 CreateWkAssetManagement: migrated (0.1639s) =============================
> 
> Migrating to CreateWkScheduling (12)
> == 12 CreateWkScheduling: migrating ===========================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_shifts, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0095s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_shift_roles, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0208s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_shift_schedules, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0152s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_public_holidays, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0243s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_users, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0266s
> -- add_column(:wk_permissions, :modules, :string, {:limit=>5})
>    -> 0.0494s
> -- execute("\t\t\t\t\tINSERT INTO wk_permissions(id, name, short_name, modules, created_at, updated_at) VALUES (3, 'SCHEDULES SHIFT', 'S_SHIFT', 'SC',                                                                                       current_timestamp, current_timestamp);\n")
>    -> 0.0038s
> -- execute("\t\t\t\t\tINSERT INTO wk_permissions(id, name, short_name,modules, created_at, updated_at) VALUES (4, 'EDIT SHIFT SCHEDULES', 'E_SHIFT', 'S                                                                                      C', current_timestamp, current_timestamp);\n")
>    -> 0.0025s
> -- execute("\t\t\t\t  UPDATE wk_permissions set modules = 'IN' where name in ('INVENTORY_VIEW', 'INVENTORY_DELETE');\n")
>    -> 0.0015s
> -- execute("\t\t\t\t  UPDATE wk_permissions set name = 'VIEW INVENTORY' where name = 'INVENTORY_VIEW';\n")
>    -> 0.0015s
> -- execute("\t\t\t\t  UPDATE wk_permissions set name = 'DELETE INVENTORY' where name = 'INVENTORY_DELETE';\n")
>    -> 0.0013s
> == 12 CreateWkScheduling: migrated (0.1748s) ==================================
> 
> Migrating to CreateWkResidentManagement (13)
> == 13 CreateWkResidentManagement: migrating ===================================
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_spent_fors, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0371s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_issues, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0598s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- adapter_name()
>    -> 0.0000s
> -- create_table(:wk_issue_assignees, {:options=>"ENGINE=InnoDB", :id=>:integer})
>    -> 0.0275s
> -- add_reference(:wk_accounts, :location, {:type=>:integer, :class=>"wk_locations", :null=>true, :index=>true})
>    -> 0.1091s
> -- add_reference(:wk_crm_contacts, :location, {:type=>:integer, :class=>"wk_locations", :null=>true, :index=>true})
>    -> 0.0346s
> -- add_reference(:wk_crm_contacts, :contact, {:type=>:integer, :class=>"wk_crm_contacts", :null=>true, :index=>true})
>    -> 0.0394s
> -- add_reference(:wk_crm_contacts, :relationship, {:type=>:integer, :class=>"wk_crm_enumerations", :null=>true, :index=>true})
>    -> 0.0362s
> -- add_reference(:wk_inventory_items, :from, {:type=>:integer, :class=>"wk_inventory_items", :index=>true})
>    -> 0.0426s
> -- execute("\t\t\t\t  UPDATE wk_inventory_items set from_id = parent_id;\n")
>    -> 0.0007s
> -- execute("\t\t\t\t  UPDATE wk_inventory_items set parent_id = null;\n")
>    -> 0.0004s
> == 13 CreateWkResidentManagement: migrated (0.3931s) ==========================
> 
> Migrating to UserSupervisor (14)
> == 14 UserSupervisor: migrating ===============================================
> -- add_column(:users, :parent_id, :integer, {})
>    -> 0.0511s
> -- add_column(:users, :lft, :integer, {})
>    -> 0.0743s
> -- add_column(:users, :rgt, :integer, {})
>    -> 0.0483s
> == 14 UserSupervisor: migrated (0.3029s) ======================================
> 
>```

After this, and after a restart, **REDMINE is not opening anymore**:

![immagine](https://user-images.githubusercontent.com/11974750/53335209-2d54f500-38fb-11e9-93ed-3ba8cfa4d86c.png)

What is the problem here? What could I check?

**Comment by andrea-ligios** [comment]
The error is 

>  Message from application: **No such file to load -- SVG/Graph/Bar.rb** (LoadError)
>  [...]
>  /opt/bitnami/apps/redmine/htdocs/plugins/redmine_wktime/app/controllers/**wkdashboard_controller.rb:5:in** `<class:WkdashboardController>'

This: 

![immagine](https://user-images.githubusercontent.com/11974750/53408534-fba56200-39be-11e9-9ba8-6fde030e3208.png)

So what??

**Comment by dhanasingh** [comment]
I think it is trying to load a dashboard and failing, can you get us the complete stacttrace from the log file ? see if you can get us more details from these 2 lines
-----------
Message from application: **No such file to load -- SVG/Graph/Bar.rb** (LoadError)
[...]
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_wktime/app/controllers/**wkdashboard_controller.rb:5:in** `class:WkdashboardController'
-----------

**Comment by andrea-ligios** [comment]
Thank you @dhanasingh , I've finally [recreated from scratch the VM and this time the installation worked](https://community.bitnami.com/t/after-installing-erpmine-3-4-on-redmine-4-0-1-redmine-doesnt-start-anymore/65045/5). 

Cheers
