### ISSUE TITLE
multiple ERP modules are nvisible

### ISSUE THREAD

**Issue by sami79** [dhanasingh/redmine_wktime#177]
Hi,
the installation goes without problem, I made the necessary configuration but I miss many module. in fact I need the inventory module. this what I got :
![image](https://user-images.githubusercontent.com/24861491/55290606-88d04200-53d5-11e9-913b-895410f0385d.png)

--------------------------

![image](https://user-images.githubusercontent.com/24861491/55290631-ee243300-53d5-11e9-8dda-8628b67b6ac2.png)

-------------------------
Environment:
  Redmine version                4.0.2.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.11.1
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.4
  additionals                    2.0.19
  computed_custom_field          1.0.7
  easy_gantt                     1.12
  easy_mindmup                   1.0
  easy_wbs                       1.5
  periodictask                   4.1.0
  redmine_blocked_reason         1.1.0
  redmine_checklists             3.1.14
  redmine_ckeditor               1.2.1
  redmine_contacts               4.2.3
  redmine_dmsf                   2.0.0
  redmine_finance                2.1.5
  redmine_issue_dynamic_edit     0.6.5
  redmine_issue_tabs             1.3.3
  redmine_issue_todo_lists       1.3
  redmine_lightbox2              0.5.0
  redmine_logs                   0.1.1
  redmine_recurring_tasks        0.3.1
  redmine_wktime                 3.5.1
  redmineup_tags                 2.0.4
  unread_issues                  2.2.4

------------------------

thank you for any help

**Comment by dhanasingh** [comment]
this is a permission issue, you will have to setup user groups for each of the modules, it can be the same croup for all modules. To setup the groups go to the administration -> plugin -> configure and then Billing, CRM, Accounting and Purchasing Tabs, setup the admin and user groups.

For inventory, scheduling and survey, go to ERPmine -> Settings -> Permissions and setup the group permission here.

Once you setup the groups, the tabs should be visible.

**Comment by sami79** [comment]
ohhh thank you M. dhanasingh, now every thing is visible. I'll try it out soon. 

another question please, is it possible to add a currency that is not listed; for exemple I'm from Tunisia and our currency is TND; is it possible that I add it ? 

thank you

**Comment by dhanasingh** [comment]
the currencies are obtained from the language files from ../config/locales/ folder.  I think for the Tunisia, you need ar-tn.yml.  you can copy that from ar.yml and make your modifications.
