### ISSUE TITLE
Why are closed issues visible in Issues selectbox?

### ISSUE THREAD

**Issue by andrea-ligios** [dhanasingh/redmine_wktime#178]
Hi,

in the latest ERPMine 3.5, under `Time & Expense`, 
**the `Issue` selectbox shows all the Issues, even the closed ones.**

I suppose that, once closed, they should disappear from the selectbox, otherwise the selectbox will become bigger than the screen in a few days...

What could I check or, if this is somehow intended, what can I do to change the behavior and have only the active issues presented in the selectbox?

Thanks in advance
Cheers

**Comment by dhanasingh** [comment]
It will show only the current week's closed issues.
It will include the previous weeks also if you have this configuration set under the plugin "Include Previous Weeks' Closed Issues"
Can you please check this ?

**Comment by andrea-ligios** [comment]
We skimmed through that checkbox, misreading it as _"include previous **week's** closed issues"_ 🤦‍♂️ 
After unchecking it, everything works fine ✌️ 
Thank you a lot @dhanasingh !
