### ISSUE TITLE
Error in version 3.6

### ISSUE THREAD

**Issue by ramezquitao** [dhanasingh/redmine_wktime#180]
I installed the V3.6 in a new redmine instance. It was not possible to change the permissions as ERPMine->Settings->permissions was not enabled to my user (a redmine admin user). I downgraded to 3.5.1, and I was able to enable all permissions to a group, and put my user to this group. Then I was able to go back to 3.6, and everything seems to be working fine.

**Comment by dhanasingh** [comment]
yeah, there seems to be a problem, but if you use the default redmine admin user (admin), it seem to work.  We are fixing this in version 3.7

**Comment by dhanasingh** [comment]
fixed in 3.7
