### ISSUE TITLE
Inventory management per project

### ISSUE THREAD

**Issue by emiliogonzalezdiaz** [dhanasingh/redmine_wktime#182]
Hi, I was looking for a redmine plugin to manage IT inventories for some specific projects in our RM server, and I came across this great plugin of yours. However, I don't find a way to restrict plugin visibility to specific groups, users or projects, which would be great.
I also wonder if you plan to manage inventories and other functionalities by project in a near future.
Thank you

**Comment by dhanasingh** [comment]
you can setup user groups with module permissions.  If you go
ERPmine -> Settings -> Permissions
you can select a group and give the 
view Inventory
Delete Inventory permissions.
then only those groups can see the inventory module.

Currently you can store inventory by location.  If we add a project dropdown next to the location dropdown would that suffice ?

**Comment by emiliogonzalezdiaz** [comment]
Hi. I understand the module level permission. What I think would be useful as well is a plugin-level permission. Only the admins and selected users/groups are allowed to access the plugin. This way, only the selected people can access the information stored by the plugin.
Yes, I think the project dropdown would be useful for the Inventory module. Maybe for other modules this functionality would be interesting as well (maybe rfq, quotes, etc?)

**Comment by dhanasingh** [comment]
This is solved in ERPmine 3.7.1, please take a look
