### ISSUE TITLE
instalaltion on redmine 3.4

### ISSUE THREAD

**Issue by perfectwebtech** [dhanasingh/redmine_wktime#183]
can u help me

i am unable to install 3.4.11 redmine 

unable to install 

-- add_column(:users, :lft, :integer)
   -> 0.3833s
-- add_column(:users, :rgt, :integer)
   -> 0.3336s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `rebuild_tree!' for #<Class:0x0000000003a36c88>
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/pwtdeveloper/public_html/plugins/redmine_wktime/db/migrate/014_user_supervisor.rb:7:in `up'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/home/pwtdeveloper/public_html/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/pwtdeveloper/public_html/lib/redmine/plugin.rb:453:in `migrate'
/home/pwtdeveloper/public_html/lib/redmine/plugin.rb:464:in `migrate'
/home/pwtdeveloper/public_html/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
NoMethodError: undefined method `rebuild_tree!' for #<Class:0x0000000003a36c88>
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/pwtdeveloper/public_html/plugins/redmine_wktime/db/migrate/014_user_supervisor.rb:7:in `up'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/home/pwtdeveloper/public_html/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/pwtdeveloper/public_html/lib/redmine/plugin.rb:453:in `migrate'
/home/pwtdeveloper/public_html/lib/redmine/plugin.rb:464:in `migrate'
/home/pwtdeveloper/public_html/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by arunkumart1995** [comment]
Which version of ERPmine did you use?

**Comment by lnh089** [comment]
> Which version of ERPmine did you use?

Hello，arunkumart,
my redmine version is 3.4.6,I have install with 3.8 version, also cannot migrate db,it show below error:
end[root@localhost redminerake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
Migrating redmine_wktime (ERPmine)...
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x000055b06e58ea20>
/opt/redmine/plugins/redmine_wktime/db/migrate/001_create_wktimes.rb:1:in `<top (required)>'
/opt/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:464:in `migrate'
/opt/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x000055b06e58ea20>
/opt/redmine/plugins/redmine_wktime/db/migrate/001_create_wktimes.rb:1:in `<top (required)>'
/opt/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:464:in `migrate'
/opt/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
[root@localhost redmine]#

**Comment by arunkumart1995** [comment]
ERPmine 3.8 is not compatible with Redmine 3.4.6.
You can try ERPmine 3.3 for redmine 3.4.6

Please refer this link for compatability
http://erpmine.org/projects/erpmine/wiki/Download?page=Download

**Comment by lnh089** [comment]
> ERPmine 3.8 is not compatible with Redmine 3.4.6.
> You can try ERPmine 3.3 for redmine 3.4.6
> 
> Please refer this link for compatability
> http://erpmine.org/projects/erpmine/wiki/Download?page=Download

thank you, now I have installed v3.3 sucess.
