### ISSUE TITLE
ERPMine Navigation bar missing

### ISSUE THREAD

**Issue by postin0** [dhanasingh/redmine_wktime#185]
![Capture](https://user-images.githubusercontent.com/23309975/64165178-b894e180-ce6e-11e9-87bb-1dbfcb4c8d87.JPG)

Hi, 
I can see ERPmine 3.7.1 plugin on my redmine 4.0 stable install. but I don't see the ERPmine on the top navigation bar.

Please help.

Thank you

**Comment by dhanasingh** [comment]
do you have the modules enabled in the plugin settings ?
And you should have permission for at least one tab in ERPmine to the ERPmine link at the top, can you please check your permissions ?

**Comment by postin0** [comment]
Hi thanks for the fast reply.
I'm new to redmine.
Plugin setting only has configure and upgrade button for erpmine. Configure button has erpmine modules but not the 'erpmine' button.
Roles and permission only has default manager, developer, & reporter
Settings projects only has sub menu modules (issues tracker, time tracker, etc)

**Comment by dhanasingh** [comment]
yes, click on the configure link for the plugin, then under general tab, select the modules you want and click save.
There should be at least one project within  redmine.

you should have the necessary permissions, for e.g for Time, you will view spent time, log time, edit own time and edit time privileges.  The privileges can be setup under admin -> roles and responsibilities. and then you will have to be a team member on a project with that role.

**Comment by postin0** [comment]
Hi, still not working
I have created a project and issue tracker
I have tried applying changes in plugin > configure > general
I have ticked all modules in roles & permission and used user with manager role 
![Capture1](https://user-images.githubusercontent.com/23309975/64241161-5cdd5d80-cf2d-11e9-9ca0-e6315679e7d2.JPG)
![Capture](https://user-images.githubusercontent.com/23309975/64241162-5cdd5d80-cf2d-11e9-8d67-d257a6fe1cb7.JPG)
![Capture2](https://user-images.githubusercontent.com/23309975/64241164-5d75f400-cf2d-11e9-9c9c-c90eb60bae60.JPG)
![Capture3](https://user-images.githubusercontent.com/23309975/64241167-5d75f400-cf2d-11e9-8b75-8f79409b8c7b.JPG)
![Capture4](https://user-images.githubusercontent.com/23309975/64241169-5d75f400-cf2d-11e9-8385-89a9fd474442.JPG)

**Comment by dhanasingh** [comment]
I think you have logged in as admin. I recommend creating another user and using that user
The permissions is given to which role ?
and do you have that role assigned to someone in your project ?

**Comment by postin0** [comment]
Its working now
Thank you so much
