### ISSUE TITLE
Reports Tab missing after installing ERPmine plugin (Adhi Software)

### ISSUE THREAD

**Issue by sushant2876** [dhanasingh/redmine_wktime#187]
Using Redmine 4.0.5.stable. Installed ERPmine plug In. However, I do not see Reports Tab. 

Reports plug in is not installed. Is it mandatory to install redmine reports plugin to see ERPmine reports? https://www.redmine.org/plugins/redmine_reporter

I am looking for a function to View/download all users clock In and Clock Out attendance reports with admin rights. But could not find this anywhere. Please advise.

**Comment by sushant2876** [comment]
<img width="642" alt="Screen Shot 2019-11-26 at 15 31 25" src="https://user-images.githubusercontent.com/58204948/69604868-ffefd000-1061-11ea-91de-671f37da59b7.png">
<img width="763" alt="Screen Shot 2019-11-26 at 15 33 09" src="https://user-images.githubusercontent.com/58204948/69604900-185fea80-1062-11ea-9272-1a7f4684d075.png">

**Comment by dhanasingh** [comment]
could be a permission issue, can you check if you have 'view reports' permission setup for your group under ERPmine -> settings -> permission

**Comment by sushant2876** [comment]
I am a Administrator. I have no group defined as Administrator. Don't see Admin user in the list. Is it mandatory to has group defined for the Admin too?
<img width="637" alt="Screen Shot 2019-11-26 at 18 31 06" src="https://user-images.githubusercontent.com/58204948/69617047-f58e0000-107a-11ea-8578-00cad4c52482.png">

**Comment by sushant2876** [comment]
Created Admin group and defined it in permissions. Now I can see Reports. But, Admin shd be allowed to see reports even without defining it, I think.
<img width="691" alt="Screen Shot 2019-11-26 at 18 33 39" src="https://user-images.githubusercontent.com/58204948/69617347-6a613a00-107b-11ea-912d-af1ef83750c7.png">

**Comment by amutha1997** [comment]
Okay, we will consider your suggestion

**Comment by sushant2876** [comment]
Thank You.
