### ISSUE TITLE
Email Notification for Leave Request

### ISSUE THREAD

**Issue by sushant2876** [dhanasingh/redmine_wktime#188]
Hi,
  We are using Leave Approval function in our organization. However, we are unable to find email notification for approvers notice if a Leave Request is submitted by the employees. Please advise if there is any way tp set the email notification or Slack Messages integration.

Thanks
Regards
Sushant

**Comment by amutha1997** [comment]
For Email notification, Did you set the supervisor role for that under user detail page?

**Comment by sushant2876** [comment]
Yes, I did. The supervisor is not receiving emails for leave request. See attached inage. 
![2F004ADE-4CEE-48B4-8486-C86E3C8E2E6E](https://user-images.githubusercontent.com/58204948/70534225-f310c780-1b9d-11ea-9aec-b86b6e8653a2.jpeg)

**Comment by amutha1997** [comment]
Do you have a Email problem here only or other redmine Email notifications. For this notification we are using submitter Email id instead of admin Email id. Could this be a problem?

**Comment by sushant2876** [comment]
We had email notification issue but now we have fixed it. We are receiving all automated emails from Redmine now. However for Leave Request, currently no email notification receives either to the Submitter or to the approver.

  Yes, submitter Email id will be a problem. When a submitter request for Leave, a notification to the Supervisor only should be sent in email and Slack Channel. That is how the supervisor can notice that a Leave Request is Submitted. After the Supervisor approves his/her leave, an automated email and SLACK notification should be sent to the submitter only.

**Comment by sushant2876** [comment]
FYI, the Leave approved message receives to the Submitter after supervisors approval.

Only the fix for notification to Supervisor when Leave Request is submitted need to be implemented.

**Comment by amutha1997** [comment]
We have implemented both request mail and approve mail. We think you have received only approve mails.
For approve mail sender is approver and the request mail sender is a submitter. We suspect your mail server is not sending submitter mails. In our next release instead of sender and approver emails, we are going to use Emission email in redmine email settings . It might fix the issue.

**Comment by sushant2876** [comment]
Working Perfect now.
