### ISSUE TITLE
Clock In and Clock Out Slack Notification

### ISSUE THREAD

**Issue by sushant2876** [dhanasingh/redmine_wktime#189]
Hello,
  We are using Clock In and Clock Out function as a Punch card of our Attendance system. We are also using Slack Integration with Redmine. Is there any way to send messages in Slack Channel when any user use the CLOCK IN or CLOCK OUT?

Thanks

Regards
Sushant

**Comment by amutha1997** [comment]
Are you saying that you want the Email notification when the user CLOCK IN and CLOCK OUT?

**Comment by sushant2876** [comment]
No, expecting Slack notifications only to a specific slack channel set in ERPMine.

**Comment by amutha1997** [comment]
Have you tried to setting up Email notifications from redmine to the slack?

**Comment by sushant2876** [comment]
Yes, we are already using message notifications to SLACK from Redmine and it is working fine.

For ERPMine, there is no setting to define a SLACK Channel for notifications. Currently, ERPMine functionalities does not support automated notification to SLACK and also do not have capability to send emails to supervisors.

There should be ability to set different SLACK Channels for:
1. Clock In and Clock Out
2. Leave Request
3. Automated email and Slack notification to all employees one day advance for Public Holidays
4. Automated email and Slack notification for employee schedule of any specific activity like project meeting etc. (Looks like scheduling is allowed for Shifts only but not small activities like meeting etc).
<img width="924" alt="Screen Shot 2019-12-13 at 15 17 05" src="https://user-images.githubusercontent.com/58204948/70773760-aa365a00-1dbb-11ea-80b3-90f772589b5f.png">

**Comment by amutha1997** [comment]
How did you setup message notification to slack from redmine?

**Comment by sushant2876** [comment]
Go to Project —> Settings —> Slack Channel
![228E7315-0827-46DD-ADAE-32DB3016A99B](https://user-images.githubusercontent.com/58204948/70787216-94cc2a80-1dd1-11ea-8c69-9668ae6fd6dc.jpeg)

**Comment by amutha1997** [comment]
I don't see the field in my redmine application. Is this through a plugin.

**Comment by sushant2876** [comment]
Yes, after installing SLACK plugin, we need to add a custom field Slack Channel for project level.

**Comment by amutha1997** [comment]
That's what we thought. The integration between Slack and ERPmine is difficult. It will create a dependency between the two. We generally avoid the dependency of other plugins.
