### ISSUE TITLE
How to create Public Holiday in Redmine

### ISSUE THREAD

**Issue by Ashjoker24** [dhanasingh/redmine_wktime#191]
I am usin Redmine version - 4.0.5 and your plugin version - 3.9. I don't have options to add public holidays. How can I add it?

**Comment by amutha1997** [comment]
Have you enabled T&E Admin privilege permission for the user?

ERPmine->settings->Permissions->T&E Admin privilege

**Comment by Ashjoker24** [comment]
yup

**Comment by amutha1997** [comment]
Are you able to go ERPmine -> HR -> Public holiday? 
There will be a empty row and option to add new rows.

![Screenshot_2020-01-14 Redmine](https://user-images.githubusercontent.com/56865314/72335569-2c7cab80-36e5-11ea-8ece-d19e258f32e0.jpg)

**Comment by Ashjoker24** [comment]
No there is no option in dashboard
![image](https://user-images.githubusercontent.com/43417210/72660827-04e55600-39f9-11ea-9d98-7bdbc80886b3.png)

**Comment by Ashjoker24** [comment]
thanks @amutha1997

**Comment by Ashjoker24** [comment]
![image](https://user-images.githubusercontent.com/43417210/72663633-d8dacc80-3a1a-11ea-8d22-8d3a41cee6b4.png)
Here there is no option to add it, but I enabled T&E Admin privilege permission for the user

**Comment by amutha1997** [comment]
Are you sure T&E admin privilege enabled for the logged in user?
Make sure that the T&E admin privilege is enabled for the logged in user's group.
