### ISSUE TITLE
Attendance module zeroing the balance leaves

### ISSUE THREAD

**Issue by abhishekj** [dhanasingh/redmine_wktime#193]
Hello,

Whenever i run the backend process as in attached screenshot for current month , it zeros the balance leaves, 

Could this be a bug or incorrect settings , please advise , i have attached the leaves settings too,

thanks
Abhishek
![unnamed](https://user-images.githubusercontent.com/1309500/72357908-c2c6c680-3711-11ea-9f81-9ed2c2ab3874.png)
![unnamed](https://user-images.githubusercontent.com/1309500/72357959-d4a86980-3711-11ea-90bd-793b16fc5065.png)

**Comment by amutha1997** [comment]
Do you have 11 as the value for "Minimum working days for leave accrual" field?
If yes, then you have to set the attendance for minimum working days to get accrual, or else
If you don't want anything, then make it blank.

**Comment by abhishekj** [comment]
Hey , 

I think it is working as expected, i will check more on this, 
thanks
Abhi
