### ISSUE TITLE
Modules not available

### ISSUE THREAD

**Issue by Ashjoker24** [dhanasingh/redmine_wktime#194]
Hi I installed your plugin redmine_wktime-3.9.0 in redmine 4.1.0 I checked all the modules available in the plugin but only 5 modules available in ERPmine plugin how can I get all module functions in ERPmine menu??
![Screenshot_4](https://user-images.githubusercontent.com/43417210/72663332-86e47780-3a17-11ea-9b11-315e989b9cd8.png)
![Screenshot_5](https://user-images.githubusercontent.com/43417210/72663333-86e47780-3a17-11ea-84ef-81a5a235e68a.png)

**Comment by amutha1997** [comment]
You have to enable the permissions to get all the modules for the user.
under, ERPmine->settings->Permissions

**Comment by Ashjoker24** [comment]
yup thanks for that now it's work fine
