### ISSUE TITLE
Punchtime in attendance import module CSV.

### ISSUE THREAD

**Issue by abhishekj** [dhanasingh/redmine_wktime#196]
Hello

For attendance module is there a way it can be imported in the attached format as in userguide?

![image](https://user-images.githubusercontent.com/1309500/73182676-7b8ffb00-413f-11ea-92a5-3e9ef785b56e.png)

I see below options:

![image](https://user-images.githubusercontent.com/1309500/73182712-89de1700-413f-11ea-8266-70d726b38b6c.png)

I have Punch time in my file,
Please advise
thanks
Abhi

**Comment by amutha1997** [comment]
Just pick Employee ID and start time as punch time.

**Comment by abhishekj** [comment]
Thanks, it works when we upload manually but not via auto Imports, any idea what i am doing wrong?

![image](https://user-images.githubusercontent.com/1309500/73910153-7ddb1d80-48d4-11ea-8a23-453b9bfef436.png)

**Comment by amutha1997** [comment]
Are you getting any errors ?

**Comment by abhishekj** [comment]
Hello, No errors, looks like the schedular didn't ran. Do I need to install any additional package or so? Thanks Abhishek Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: amutha1997 <notifications@github.com> Date: 06/02/2020  17:43  (GMT+05:30) To: dhanasingh/redmine_wktime <redmine_wktime@noreply.github.com> Cc: Abhishek Jain <abhishek.netjain@gmail.com>, Author <author@noreply.github.com> Subject: Re: [dhanasingh/redmine_wktime] Punchtime in attendance import module CSV. (#196) Are you getting any errors ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dhanasingh/redmine_wktime/issues/196?email_source=notifications\u0026email_token=AAJ7WPFSGVZ4YIA3JYS4HALRBP5HPA5CNFSM4KMCHBFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK7AGSY#issuecomment-582878027",
"url": "https://github.com/dhanasingh/redmine_wktime/issues/196?email_source=notifications\u0026email_token=AAJ7WPFSGVZ4YIA3JYS4HALRBP5HPA5CNFSM4KMCHBFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK7AGSY#issuecomment-582878027",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by amutha1997** [comment]
No. You don't need to install anything additionally.

We are using Rufus scheduler for running rails job. For Rufus-scheduler to work, the rails application should be up all the time.
Are you using Apache Passenger?
If you are using Apache Passenger module then make sure the following settings are made
a) PassengerMinInstances 1
b) RailsAppSpawnerIdleTime 0
