### ISSUE TITLE
ERPmine -> HR -> Clock In/Out uses different Date and Time Zone for multi geography users.

### ISSUE THREAD

**Issue by sushant2876** [dhanasingh/redmine_wktime#199]
If server time zone is India e.g March 09 time 21:17, but the user is in another time zone e.g. JAPAN March 10 at time 00:47 am.

Attendance takes the users local date but servers clock time.

Attached is the snap shot of My Environment
<img width="1205" alt="Screen Shot 2020-03-10 at 16 17 45" src="https://user-images.githubusercontent.com/58204948/76289347-43f2a200-62ec-11ea-853f-ee6173cc0ee3.png">

**Comment by amutha1997** [comment]
Okay, we will take a  look.

**Comment by amutha1997** [comment]
This issue is fixed in 4.0 . 4.0 is released, Please take a look.
