### ISSUE TITLE
Automatic rounding of invoice amount should be configurable.

### ISSUE THREAD

**Issue by jpsaman** [dhanasingh/redmine_wktime#203]
After taxes have been applied to a new invoice it gets automatic an item entry "Round Off", which rounds the total amount. The resulting amount of the invoice to bill a customer is not correct because of the rounding. In my use case such rounding should not occur. 

The "Round Off" item should be configurable.

**Comment by amutha1997** [comment]
This issue is fixed in 4.0 .  4.0 is released, Please take a look.

**Comment by jpsaman** [comment]
Looks good. 

Also the historic invoice are not rounded, when the option is off.

Thanks for fixing my pathetic attempt to implement this feature ;)
