### ISSUE TITLE
Log time on issue is not possible

### ISSUE THREAD

**Issue by sherwood333** [dhanasingh/redmine_wktime#206]
Redmine version: 4.1.1
wk_time vesion: 3.9.2 (and 3.9.3)
(Tested on a clean installation of Redmine)

When trying to log time on a ticket, an error shows up "User is invalid.". (The log time while editing ticket details does work correctly).

When we set the permission "Log time for other users" to a user, that user can then log time for himself (and others!). This workaround is not possible for us.

**Comment by Arun-TAK** [comment]
if you tried in Redmine 4.1.0, We tried, It is working fine in Redmine 4.1.0

**Comment by imendiola** [comment]
Same error for me, with Redmine 4.1.1 and wk_time 3.9.3. And same behaviour, activating the "Log spent time for other users" permission allows the user to create the entries

**Comment by sherwood333** [comment]
We have just completed the migration to 4.1.1, It would sadly cost too much to do another migration to a different version of Redmine.

**Comment by amutha1997** [comment]
Ok, we will take a look.

**Comment by sherwood333** [comment]
Hello, Is there any updates about this bug? Thanks in advance!

**Comment by amutha1997** [comment]
This might come in 4.0.1 which may be released next week.

**Comment by sherwood333** [comment]
Great news!

**Comment by amutha1997** [comment]
4.0.1 is released, Please take a look.

**Comment by imendiola** [comment]
It is working correctly now in 4.0.1 release. Than you so much!

**Comment by sherwood333** [comment]
Spinning up a test server now. Will let you know in a couple of hours.

**Comment by sherwood333** [comment]
Test works!
Thank you for your time.

**Comment by sherwood333** [comment]
On further inspection, time entries are now non-editable on the timesheet. Am i missing a setting on our test server? A developer should be able to edit his own hours in the timesheet.

**Comment by imendiola** [comment]
Do you have this permission set?

![imagen](https://user-images.githubusercontent.com/16780639/88040761-a9338b00-cb49-11ea-8eb2-b0d95b5c07ef.png)

**Comment by sherwood333** [comment]
Somehow the permission got reset. My bad!

Issue is resolved!
