### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zonork** [dhanasingh/redmine_wktime#21]
i install the plugin but when ill try use have this:

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

**Comment by Zonork** [comment]
Logs: Migrating to CreateWktimes (1)
DEPRECATION WARNING: `#timestamp` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /home/redmine/redmine/plugins/redmine_wktime/db/migrate/001_create_wktimes.rb:13)
Migrating to CreateWkExpenseEntries (2)
DEPRECATION WARNING: `#timestamp` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /home/redmine/redmine/plugins/redmine_wktime/db/migrate/002_create_wk_expense_entries.rb:31)

**Comment by suganya-thulasiraman** [comment]
Fixed in 1.9
