### ISSUE TITLE
Server error saving Timesheet

### ISSUE THREAD

**Issue by sherwood333** [dhanasingh/redmine_wktime#211]
Hello,

After installing the latest update for wk_time (from 3.9.2 to 4.0.1 to 4.0.2) we noticed that saving the timesheet will throw a server side error (500)

```
Completed 500 Internal Server Error in 75ms (ActiveRecord: 29.2ms)

NoMethodError (undefined method `[]=' for nil:NilClass):

plugins/redmine_wktime/app/controllers/wktime_controller.rb:1433:in `block (2 levels) in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1427:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1427:in `each_with_index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1427:in `block in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1411:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1411:in `each_with_index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1411:in `gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:183:in `update'
```

Using versions:

Wk_Time version 4.0.2
redmine version 4.1.1

**Comment by amutha1997** [comment]
We are unable to reproduce this problem, is it possible for you to  share your timesheet screenshot which was failing ? I mean before save.

What ruby and rails version are you using ?

**Comment by sherwood333** [comment]
It looks like a save without adding a new row works as expected.

![image](https://user-images.githubusercontent.com/7136704/88517401-4d03b780-cfde-11ea-9a59-e7edb82ae8d6.png)

I've added the last row in this image. Once this row is added, the time sheet fails to save.

**Comment by sherwood333** [comment]
$ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

$ rails --version
Rails 5.2.4.2

**Comment by amutha1997** [comment]
This issue is fixed in 4.0.3 . 4.0.3 is released, Please take a look.

**Comment by sherwood333** [comment]
Will do!

**Comment by sherwood333** [comment]
Seems to be working. Thanks for your quick fix!
