### ISSUE TITLE
New timesheet project's list

### ISSUE THREAD

**Issue by ltufari** [dhanasingh/redmine_wktime#214]
Hi! When I click on the "New Timesheet" button, I have to setup some settings (Project, Member, Start date, Previous Week's Template and Sheet view). Unfortunately I can see in the list of the projects only that ones in which I'm involved as Manager or Project Manager. However, if I enter in the edit page I can (correctly) add timesheet for all my projects. This behaviour can confuse the users: is that possibile to avoid this selection? Can I enter directly in the new timesheet page (starting by default on the current week)? Can I avoid Manager and PM can change other users timesheet?

Many thanks for the answer and for this plugin!

**Comment by amutha1997** [comment]
We will take the request to go to timesheet page directly and put it for our next release.
Regarding managers editing subordinate's timesheet, you can restrict by not giving the 'Edit Time log' permission.

**Comment by ltufari** [comment]
Perfect, thank you!
