### ISSUE TITLE
Error while updateting the plugin

### ISSUE THREAD

**Issue by sekai-parag** [dhanasingh/redmine_wktime#217]
I copy the file to the plugin folder and execute the migration command 
` rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production`
But an error occur and migration is aborted.
below are the errors I got.  _I am new in Ruby and just managing the server._ 
`/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Migrating redmine_wktime (ERPmine)...
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x0000000002911868>
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/share/redmine/plugins/redmine_wktime/db/migrate/020_create_wk_income_tax.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:958:in `block in migrate'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/share/redmine/lib/redmine/plugin.rb:453:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:464:in `migrate'
/usr/share/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x0000000002911868>
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/share/redmine/plugins/redmine_wktime/db/migrate/020_create_wk_income_tax.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/share/redmine/lib/redmine/plugin.rb:453:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:464:in `migrate'
/usr/share/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
`
How to solve this issue.

**Comment by dhanasingh** [comment]
what version of redmine, erpmine, rails, mysql, linux etc are you using ?
