### ISSUE TITLE
redmine_wktime 1.8 on redmine 3.0.1

### ISSUE THREAD

**Issue by Zonork** [dhanasingh/redmine_wktime#22]
i install i can access to configuration but whe i try to work with the plugin still having this: 

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

error log:

Started GET "/users" for 127.0.0.1 at 2015-06-01 17:24:42 +0000
Processing by UsersController#index as HTML
  Current user: admin (id=1)
  Rendered users/index.html.erb within layouts/admin (29.1ms)
  Rendered admin/_menu.html.erb (8.2ms)
  Rendered layouts/base.html.erb (30.1ms)
Completed 200 OK in 204ms (Views: 57.6ms | ActiveRecord: 47.3ms)
Started GET "/wktime/index" for 127.0.0.1 at 2015-06-01 17:32:42 +0000
Processing by WktimeController#index as HTML
  Current user: admin (id=1)
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ... (users.type='User' AND users.status=1)  ORDER BY users.firs...
                                                             ^
: SELECT DISTINCT "members".* FROM "members" INNER JOIN "users" ON "users"."id" = "members"."user_id" INNER JOIN "member_roles" ON "member_roles"."member_id" = "members"."id" INNER JOIN "roles" ON "roles"."id" = "member_roles"."role_id" WHERE "members"."project_id" = $1 AND (users.type='User' AND users.status=1)  ORDER BY users.firstname ASC,users.lastname ASC
Completed 500 Internal Server Error in 34ms

ActiveRecord::StatementInvalid (PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ... (users.type='User' AND users.status=1)  ORDER BY users.firs...
                                                             ^
: SELECT DISTINCT "members".* FROM "members" INNER JOIN "users" ON "users"."id" = "members"."user_id" INNER JOIN "member_roles" ON "member_roles"."member_id" = "members"."id" INNER JOIN "roles" ON "roles"."id" = "member_roles"."role_id" WHERE "members"."project_id" = $1 AND (users.type='User' AND users.status=1)  ORDER BY users.firstname ASC,users.lastname ASC):
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare_statement'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_cache'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/association_relation.rb:19:in `exec_queries'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `collect'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:1071:in `setgroups'
  plugins/redmine_wktime/app/controllers/wktime_controller.rb:26:in `index'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-xml_parser-1.0.1/lib/action_dispatch/xml_params_parser.rb:16:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'

**Comment by suganya-thulasiraman** [comment]
Are you using Postgres?
If yes, please refer issue #17 for the fix

**Comment by suganya-thulasiraman** [comment]
Fixed in 1.9
