### ISSUE TITLE
Problem with Billing/Contracts tab

### ISSUE THREAD

**Issue by LorneMalvo77** [dhanasingh/redmine_wktime#220]
Hi!
I am getting internal error trying to access Billing/Contracts tab. I am using Redmine 4.1.1 with wktime 4.0.4 on Ubuntu 18.04. This is what I found in the log:

Completed 500 Internal Server Error in 41ms (ActiveRecord: 7.9ms)

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    17:                                 <tr>
    18:                                           <td class="lbl-txt-align"><%=h entry.contract_number %></td>
    19:                                           <td class="lbl-txt-align"><%=h entry.parent_type == 'WkAccount' ? 'Account' : 'Contact' %></td>
    20:                                           <td class="lbl-txt-align"><%=h entry.parent.name %></td>
    21:                                           <td class="lbl-txt-align"><%=h entry.project.blank? ? "" : entry.project.name %></td>                               $
    22:                                           <td class="lbl-txt-align"><%=h entry.start_date %></td>
    23:                                           <td class="lbl-txt-align"><%=h entry.end_date %></td>

Can you guide me what can cause this issue? Thanks in advance.

**Comment by amutha1997** [comment]
Thanks for using erpmine, this seems to be a bug we will fix it in the next release, in the mean time, can you replace this file /plugins/redmine_wktime/app/views/wkcontract  with the attached file and let us know if it works for you.
[_contract_list.html.zip](https://github.com/dhanasingh/redmine_wktime/files/5391735/_contract_list.html.zip)

**Comment by LorneMalvo77** [comment]
Works great! Thank you for the answer and for your effort!
