### ISSUE TITLE
Leave Type dropdown has no values

### ISSUE THREAD

**Issue by monudjn** [dhanasingh/redmine_wktime#222]
While creating a new leave request, leave type drop down has no values. How do we create leave types? We dont see any documentation around this

**Comment by dhanasingh** [comment]
leave types are created in Administration ->Plugins -> Attendance -> Leave
Leave types are nothing but an issue in a project.  you can use that leave to log time also in your timesheet
<img width="689" alt="Screenshot 2020-10-21 at 8 59 18 PM" src="https://user-images.githubusercontent.com/1752400/96742333-64d1b880-13e0-11eb-83b5-069879489a06.png">

**Comment by monudjn** [comment]
> leave types are created in Administration ->Plugins -> Attendance -> Leave
> Leave types are nothing but an issue in a project. you can use that leave to log time also in your timesheet
> <img alt="Screenshot 2020-10-21 at 8 59 18 PM" width="689" src="https://user-images.githubusercontent.com/1752400/96742333-64d1b880-13e0-11eb-83b5-069879489a06.png">

Thanks @dhanasingh . Its bit tricky but able to add leave types. Is it possible to send leave request to managers or some groups?

**Comment by amutha1997** [comment]
The supervisor will get the email notification, Supervisor can be set in User detail page.
![user page1](https://user-images.githubusercontent.com/56865314/96837114-8758e580-1463-11eb-8058-e8d8f3168a90.png)
If you want additional people to get the notification, put them in a user group and set the leave notification permission for that group. "Settings -> Permission -> Select Group -> Check Receive Leave Notification".
