### ISSUE TITLE
Currency is always $

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#223]
I have choosed € in the Plugin->Configuration -> General page, but in every page the dropdownbox shows as default the $ currency...is there any possibility to change it?

**Comment by amutha1997** [comment]
This issue is fixed in 4.1.  4.1 is released, Please take a look.

**Comment by CSCSxx** [comment]
Great, i have test it.
Module Purchasing seems to work perfect.
In Inventory Modul -> New Item it works also, but not under New Shipment.

**Comment by CSCSxx** [comment]
And there is another "little thing" .. the Unit of Messure shows always fist alphabetical entry, not the in Product selected entry

**Comment by amutha1997** [comment]
We will take a look and get it fixed in the next release.

**Comment by CSCSxx** [comment]
The two problems are still present at v4.1.1

**Comment by amutha1997** [comment]
We will fix the issue in next release.

**Comment by amutha1997** [comment]
This issue is fixed in 4.2. 4.2 is released, Please take a look.

**Comment by CSCSxx** [comment]
Both points are working now - Great Job!
