### ISSUE TITLE
Spent time Options not available in german language

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#226]
If i set the default language in redmine to german (equal if i set manual my user to english), the Option "Spent Type (Time/Expense/Material/...)" in site Spent time is not available, but works perfect if i set my language in english...

**Comment by amutha1997** [comment]
We will take a look and get it fixed in the next release.

**Comment by amutha1997** [comment]
This issue is fixed in 4.2. 4.2 is released, please take a look.

**Comment by CSCSxx** [comment]
Great Job - now i can see it also in german ... thanks!
