### ISSUE TITLE
Cannot enter spent time on non-assigned issue

### ISSUE THREAD

**Issue by jmtemmos** [dhanasingh/redmine_wktime#229]
Sometimes, a task can change of assignee, depending on the status. In this case, it is not possible to select a task to assign time on it, unless it is currently assigned to the user.

=> should be able to assign time on (at least) watched issue

**Comment by amutha1997** [comment]
It depends on your project's Role's issue visibility ? what issue visibility do you have ?

![screenshot1](https://user-images.githubusercontent.com/56865314/107776328-6d6f4580-6d67-11eb-8c66-7975671129be.png)

Please check whether 'Allow User filtering to My Issue' is turned off

![screenshot3](https://user-images.githubusercontent.com/56865314/107778646-541bc880-6d6a-11eb-8f90-ebe17b339d31.png)

**Comment by jmtemmos** [comment]
Hello. Thanks a lot.
The "Allow User filtering to My Issues" option did the trick. In fact the
french translation for this option is misleading.

Problem solved !

Thanks





Le ven. 12 févr. 2021 à 15:14, amutha1997 <notifications@github.com> a
écrit :
