### ISSUE TITLE
New Model not avaible under New Shipment before publishing in Items

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#230]
After i created a new model in a brand, i can't select it in the module New Shipment. First i have to go to Items->New Item and create the item without Additional Information. Is this right ?

**Comment by amutha1997** [comment]
We will fix the issue in next release.

**Comment by amutha1997** [comment]
Yes, you are right, you have to create the item with the combination of brand and model before using that in the shipment.

**Comment by CSCSxx** [comment]
Ok, then i made everything right ;)
Thanks for your help.
