### ISSUE TITLE
Shipping Module - Over Head Cost error

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#231]
In one Position there is an Item with a quantity of 3, a cost price of 10 and a over head cost of 5 then the right summary is: 3x10+5= 35. But in the Overview of shipments is displayed 45 wich means 3x10+3x5 ... in my opinion it is not right...

**Comment by amutha1997** [comment]
We will fix the issue in next release.

**Comment by amutha1997** [comment]
This issue is fixed in 4.3. 4.3 is released, Please take a look.

**Comment by CSCSxx** [comment]
It works 🥇
