### ISSUE TITLE
Show on Map option not visibile in HR module

### ISSUE THREAD

**Issue by meetdileep** [dhanasingh/redmine_wktime#232]
Hello,

Hope you are all doing well.

I am just exploring attendance module in ERPmine 4.1 version, show on map option is not visible and also it is observed that geolocation values are not getting stored.

Could anyone please help on this issue.

**Comment by amutha1997** [comment]
Have you turned on geolocation config?
plugins -> Time & Expense->save geolocation
plugins -> Attendance ->save geolocation

![screenshot](https://user-images.githubusercontent.com/56865314/107373722-d4dd8900-6b0c-11eb-9866-bff7e47030e0.png)

**Comment by meetdileep** [comment]
Yes. I have checked the Save GeoLocation option, still it is not visible.

**Comment by meetdileep** [comment]
![erpmineattendance](https://user-images.githubusercontent.com/3448227/107602647-3eb27b80-6c50-11eb-8b5e-53dded9a7d0f.png)

**Comment by amutha1997** [comment]
There is a bug, you have to turn on time & expense geo location also, did you turn that on ? the every first time, the browser would have asked for permission to use location service, did you allow it ? if not, please clear the browser cache and allow it again.
 
Are you clocking in and out using the clock icon at the top right corner ?

**Comment by meetdileep** [comment]
Hi Amutha,
Very Sorry for delayed response. We are able to see the option now after enabling Time & Expense. Thank you very much. It is good if that is not linked with Time & Expense.

**Comment by amutha1997** [comment]
We will fix this in the next release of ERPmine 4.2.1

Amutha
An upcoming Webinar on ERPmine Time & Expense on April 28 2021, 3PM IST (+5:30 GMT) , 
Please click here to register if interested
https://us02web.zoom.us/meeting/register/tZcrcOCvqTouGNALBqMGF1GuxyKYjqAcesyM

**Comment by amutha1997** [comment]
This issue is fixed in 4.2.1. 4.2.1 is released, Please take a look.

An upcoming Webinar on ERPmine – Attendance on May 25, 2021, 6 PM IST (GMT+5:30),

Please click here to register if interested
https://rebrand.ly/jf582oc

*Topics* :

* Clock In/Clock Out
* Review Leave Status
* Leave Request
* Integrate with Attendance Devices
* Attendance Report
* Attendance on Map
* Mobile App
