### ISSUE TITLE
Crypted Output at spent Time

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#236]
Please see picture:
![Spent Time Error](https://user-images.githubusercontent.com/156014/112467697-a982c680-8d67-11eb-9267-7712b07adad6.png)

**Comment by amutha1997** [comment]
We will fix the issue in next release.

Amutha
An upcoming Webinar on ERPmine Time & Expense on April 28 2021, 3PM IST (+5:30 GMT) ,
Please click here to register if interested
https://us02web.zoom.us/meeting/register/tZcrcOCvqTouGNALBqMGF1GuxyKYjqAcesyM

**Comment by amutha1997** [comment]
This issue is fixed in 4.3. 4.3 is released, Please take a look.

**Comment by CSCSxx** [comment]
It works. Great Job!
