### ISSUE TITLE
time_entries Redmine 500 error

### ISSUE THREAD

**Issue by LeszekS72** [dhanasingh/redmine_wktime#237]
No access to edit time_entries:
![error500_e_t](https://user-images.githubusercontent.com/82021154/113677500-f0ed4900-96bd-11eb-86eb-735657131eb4.jpg)

Started GET "/time_entries/4/edit" for 192.168.0.10 at 2021-04-02 12:16:10 +0000
Processing by TimelogController#edit as HTML
  Parameters: {"id"=>"4"}
  Current user: admin (id=5)
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.4ms)
  
NoMethodError (undefined method `id=' for nil:NilClass):
  
plugins/redmine_wktime/lib/timelogcontroller_patch.rb:495:in `find_time_entry'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by amutha1997** [comment]
What version of redmine and erpmine are you using?

**Comment by LeszekS72** [comment]
Redmine 4.1.1,  i tried the two last erpmine version, 4.1 and 4.2

**Comment by LeszekS72** [comment]
I tried editing an expense. You were right, entering the time solved the problem with accessing editing entries.
Thank you.

**Comment by amutha1997** [comment]
This issue is fixed in 4.3. 4.3 is released, Please take a look.
