### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#238]
[wktime_de.zip](https://github.com/dhanasingh/redmine_wktime/files/6382212/wktime_de.zip)
The latest german translation i use...

**Comment by amutha1997** [comment]
Thank you, we will put it in the next release

Amutha
An upcoming Webinar on ERPmine Time & Expense on April 28 2021, 3PM IST (GMT+5:30).

Please click here to register if interested,
https://us02web.zoom.us/meeting/register/tZcrcOCvqTouGNALBqMGF1GuxyKYjqAcesyM

Topics:
- Attachments
- Project Based Approvals
- Issue Logger
- Timesheet on Map
- Timesheet Report
- Mobile App

**Comment by CSCSxx** [comment]
I have created a pull request with new translation fitting V4.2.1

**Comment by CSCSxx** [comment]
File is migrated in dev
