### ISSUE TITLE
Redmine 4.2.x compatible ?

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#239]
We are currently using Redmine version 4.1.2 and ERPMine 4.2 and are currently considering upgrading to Redmine 4.2.1.
Is ERPMine 4.2 already compatible with it? According to www.erpmine.com, this version can only run with Redmine 4.1.1.

**Comment by amutha1997** [comment]
We haven’t tested ERPmine 4.2 with Redmine 4.2. But we are releasing ERPmine 4.2.1 next week which will be compatible with Redmine 4.2.

**Comment by CSCSxx** [comment]
Perfect :)
