### ISSUE TITLE
New Spent of material not possible since Update to 4.3

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#244]
When trying to spent new material to a ticket it come "Project can not be empty"
But in the formula there is no choice of project avaible (only the ticket) ...
![image](https://user-images.githubusercontent.com/156014/124500716-89c85900-ddc0-11eb-90de-517b447c8f66.png)

**Comment by amutha1997** [comment]
We will fix this in the next release, in the interim, can you please replace this file timelogcontroller_patch.rb in plugins/redmine_wktime/lib/timelogcontroller_patch.rb

[timelogcontroller_patch.zip](https://github.com/dhanasingh/redmine_wktime/files/6770928/timelogcontroller_patch.zip)

**Comment by CSCSxx** [comment]
Patch works 🥇 
Feel free to close the issue.
Thanks for this quick response and help!

**Comment by amutha1997** [comment]
This issue is fixed in 4.3.1. 4.3.1 is released, Please take a look.
