### ISSUE TITLE
Need a better responsive design or add horizontal overflow

### ISSUE THREAD

**Issue by shawndibble** [dhanasingh/redmine_wktime#25]
Right now, if your screen is too small for the timesheet, the right side gets cut off. It would be nice if the table was responsive. A quick fix would be: overflow-x: auto; applied to the table. This way the user could horizontally scroll if needed.

**Comment by suganya-thulasiraman** [comment]
Ok. We will take a look.

**Comment by suganya-thulasiraman** [comment]
We have tested T&E on Firefox and Chrome in windows 7 & 8, we are getting the horizontal scroll bar.
Which browser and what OS do you use?

**Comment by shawndibble** [comment]
must be my theme then, thank you.

I am using PurpleMine2 for my theme.
