### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by surebrec** [dhanasingh/redmine_wktime#252]
i am using Bitnami virtual machine with Redmine installed. I download and unzip wktime plugin (https://erpmine.org/attachments/download/75/redmine_wktime.zip), move it to plugins folder. install gem rufus scheduler. and i cant apply migration:

```
rake aborted!
No Rakefile found
```

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.8-p224 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql
ERPMine 4.2
```

**Comment by amutha1997** [comment]
Can you send details from the log file?

**Comment by surebrec** [comment]
> Can you send details from the log file?

i don't know where the log file is located. i create a small online doc with my steps:
https://docs.google.com/document/d/130VwcK7Qu6A6hNlad8kDBMjcSiymOGeEx7HyHtK8Bnc/edit?usp=sharing

I really appreciate your help

**Comment by amutha1997** [comment]
rake redmine:plugins:migrate NAME=redmine_wktime RAILS_ENV=production
Run the db migration script from the root redmine folder.

log file location redmine/ log/production.log

**Comment by surebrec** [comment]
![image](https://user-images.githubusercontent.com/2479993/132714446-8ea861b0-8fc0-491b-9bc5-20d7726e7294.png)

here is the log:
[production.log](https://github.com/dhanasingh/redmine_wktime/files/7138755/production.log)

**Comment by shreyarajwade** [comment]
@surebrec you need to run 'bundle config unset deployment' and then run 'bundle install' again. That should help fix this.
Hope this helps.
