### ISSUE TITLE
Log Materials to Issues

### ISSUE THREAD

**Issue by alloattialejandro** [dhanasingh/redmine_wktime#254]
When I add TimeSpent material to an issue, there isn't any comment on the issue.

is it possible to add a comment with item and quantity?

**Comment by amutha1997** [comment]
We changed the product column to product items on the spent time list page. Is it work for you?

![Product item](https://user-images.githubusercontent.com/56865314/143823122-e9f95c35-0634-440d-8abe-f230592aee17.jpeg)

**Comment by alloattialejandro** [comment]
That's great! Thanks
