### ISSUE TITLE
Field for entering Leave Type values is missing 

### ISSUE THREAD

**Issue by albenik85** [dhanasingh/redmine_wktime#270]
Similar to what was reported in https://github.com/dhanasingh/redmine_wktime/issues/222, we are missing input values for the leave type. I don't know whether it is related to a newer version (ERPmine 4.6 on redmine 5.0.2) or related on the german translation, but when we go to Administration --> Pluigns --> ERPmine --> Attendance as described in the solution mentioned above (and in the documentation), we are missing the leave field: 
![image](https://user-images.githubusercontent.com/81562690/178916684-282b7e41-c389-4226-9d73-cf013e7ceb3b.png)

**Comment by cdhana17** [comment]
Thanks for using our ERPmine

The leave setting has been moved to the HR module.  Please click that 3 Dots in the HR Module HR -> Leave -> 
> Leave setting.  You can see in the screenshot
![leave settings updated](https://user-images.githubusercontent.com/20320262/178926975-2438bb15-0adc-40b1-969d-129a3016ba3b.png)

**Comment by albenik85** [comment]
Thanks a lot for the quick response!

**Comment by cdhana17** [comment]
Please click ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege
