### ISSUE TITLE
Field for entering Leave Type values is missing again

### ISSUE THREAD

**Issue by vbe-phucle** [dhanasingh/redmine_wktime#272]
Similar to what was reported in #222 and #270, we are missing input values for the leave type. 

I don't know whether it is related to a newer version (ERPmine 4.6 on redmine 5.0.2), but when we go to Administration --> Pluigns --> ERPmine --> Attendance as described in the solution mentioned above (and in the documentation), we are missing the leave field:

Following to what was reported in #270, but when we go to the HR Module HR -> Leave -> as described in the solution above, the 3 Dots is missing.

![ERPmine 2022-08-30 164623](https://user-images.githubusercontent.com/101711305/187412467-7f74d7e6-5ccd-4ce7-a34c-342c7e587603.jpg)

![ERPmine 2022-08-30 171451](https://user-images.githubusercontent.com/101711305/187412316-4001b8d1-496c-4e2b-9b6c-8f171bbadfd9.jpg)

**Comment by cdhana17** [comment]
Please click ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege

**Comment by vbe-phucle** [comment]
Thanks @cdhana17  for quick response.

We did click ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege. 
But when we went back to Permission, there is no check for "Enable Admin Attendance Privilege".
And the 3 Dots is missing.

![ERPmin 2022-08-31 094904](https://user-images.githubusercontent.com/101711305/187582298-5d7b21c1-b7c0-4f72-a6c9-76e90da9f26e.jpg)

![ERPmine 2022-08-31 095004](https://user-images.githubusercontent.com/101711305/187583713-bbe89621-c854-4376-b9e4-41236fe6033e.jpg)

![Redmine 2022-08-31 095053](https://user-images.githubusercontent.com/101711305/187583771-66194b2f-d2a5-4f0d-b24b-e355b8f7b836.jpg)

**Comment by vbe-phucle** [comment]
Hi @cdhana17 

We have found a solution.  We do following steps to apply ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege

Step 1: Redmine --> Administration --> Groups --> New Group : To create a group name like Group_Admin
Step 2: Redmine --> Administration --> Users --> To assign a user to Group_Admin
Step 3: Under a user, ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege : Save it.
Step 4: Go back to Permission, there is a check for "Enable Admin Attendance Privilege".
Step 5: The 3 Dots appears.

It works.

Again. Thanks @cdhana17
