### ISSUE TITLE
Deprecation of rss_key

### ISSUE THREAD

**Issue by padevotozerobug** [dhanasingh/redmine_wktime#277]
Redmine 5 is logging a warning related to deprecation of rss_key

DEPRECATION WARNING: User.rss_key is deprecated and will be removed in Redmine 6.0. Please use User.atom_key instead. (called from block in _plugins_redmine_wktime_app_views_wktime__edit_footer_html_erb__4059059400697648642_84900 at /opt/redmine-5.0.4/plugins/redmine_wktime/app/views/wktime/_edit_footer.html.erb:11)

**Comment by cdhana17** [comment]
This issue is fixed in 4.7. 4.7 is released, Please take a look.
