### ISSUE TITLE
Can't add leave type

### ISSUE THREAD

**Issue by skrzypaczdawid** [dhanasingh/redmine_wktime#278]
Hi, I'm using latest (4.6) version of the plugin. 
I am facing an issue where I can't add or edit any leave type. In fact on drop-down menu there isn't any type to choose from. Is there any guide to add leave type?
I searched every place I could think of (settings of plugin, administration of plugin)

**Comment by cdhana17** [comment]
Hi,
Please click ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege
And then You can Create leave types in HR -> Leave  -> Leave settings. 

![Screenshot 2023-02-27 at 6 35 52 PM](https://user-images.githubusercontent.com/20320262/221572975-b4c5bb3f-aadf-41be-9ba5-03bd964c19f1.png)

**Comment by skrzypaczdawid** [comment]
Thanks a lot!

**Comment by rosso-** [comment]
Same problem, but version is 3.9. 
Know how?

**Comment by cdhana17** [comment]
Hi,
Leave types are created in Administration ->Plugins -> Attendance -> Leave
Leave types are nothing but an issue in a project
<img width="689" alt="leave config" src="https://github.com/dhanasingh/redmine_wktime/assets/20320262/c7b230b3-d5cf-4c93-85a9-4a92f3974d1a">
