### ISSUE TITLE
CRM > Contacts not populating Contact list for other forms

### ISSUE THREAD

**Issue by Draekmus** [dhanasingh/redmine_wktime#282]
Hello,
I have noticed that, when I add a contact in the CRM module, that it is not populating that name to lists referencing Contact.

For example, if I go into Billing > Invoice, and choose to filter by Contact, the list is blank.

This seems to affect contacts regardless if they are associated with an account/opportunity/lead or not.

Is this a glitch?  Not yet implemented?  Or am I missing something with how Contacts are handled?

Both the latest stable (4.6) and Git versions of ERPMine have this issue for me.

I am using Redmine 5.0.4, with PostgreSQL 15 as the database backend.

**Comment by Draekmus** [comment]
@cdhana17 Unfortunately, that has not worked.  I cannot associate the contact with the project because the Name drop-down box is empty.

I did find the solution to my problem: contacts will not appear on any list if they do not have an email address associated with them.  As soon as I put in an address, they started populating the list.

This is specific to Contacts only and does not affect Accounts, Leads, or Opportunities as far as I could tell.

Should email addresses be required for Contacts?

**Comment by cdhana17** [comment]
ok, we will take a look

**Comment by cdhana17** [comment]
This issue is fixed in 4.7. 4.7 is released, Please take a look.
