### ISSUE TITLE
Does not list tasks for time posting

### ISSUE THREAD

**Issue by adrianobr** [dhanasingh/redmine_wktime#283]
I would like to edit or re-release some times.
I made the selection of the project but the related tasks are not loaded.
Redmine 4.2
ERP Mine 4.2

![erp_mine](https://user-images.githubusercontent.com/7975205/222830682-68d65ca6-7421-4cd5-ae0a-7b56bb21982f.png)

**Comment by cdhana17** [comment]
Please click Administration–> Plugin-> Configure–> Time and Expenses

If you have enabled "Allow User Filtering for My Issues" in settings, please turn off


![Untitled](https://user-images.githubusercontent.com/20320262/223038378-6ee88184-ffec-4883-a427-d6e3e08f18b6.png)

**Comment by adrianobr** [comment]
thanks so much!
Have a nice day!
