### ISSUE TITLE
how to add leave types

### ISSUE THREAD

**Issue by nanaksingh13** [dhanasingh/redmine_wktime#284]

**Comment by cdhana17** [comment]
Hi,
Please click ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege
And then You can Create leave types in HR -> Leave -> Leave settings.

![221572975-b4c5bb3f-aadf-41be-9ba5-03bd964c19f1](https://user-images.githubusercontent.com/20320262/224613468-0d598f0d-77ec-4133-a861-7960445c433d.png)
