### ISSUE TITLE
No where to configure leave types in Redmine 5.0.5

### ISSUE THREAD

**Issue by Raw1mage** [dhanasingh/redmine_wktime#293]
2023 August
erpmine plugins installed with redmine in docker environment
Redmine 5.0.5, redmine_wktime 4.7

Troubled problem: 
No where to configure leave types ?
The funciton of "New Leave Request" shows a blank Leave type, and the submission form does not accept a blank leave type.

Same happens to the schedule shifting funcitons.

Fresh installed twice and the problem persists.  Need an enlightment.
Thanks.

PS.  remine is running in locales=zh_TW

**Comment by cdhana17** [comment]
Hi,
For leave type
Please click ERPmine –> Setting-> Permission –> Enable Admin Attendance Privilege
And then You can Create leave types in HR -> Leave -> Leave settings.
![leavetype](https://github.com/dhanasingh/redmine_wktime/assets/20320262/627f32f8-1061-415d-bc9f-de25952a7ce2)

For Shift scheduling 
Click ERPmine –> Setting-> Permission –> Enable Schedules shift and Edit shift schedules
And then You can Create shifts in HR -> scheduling -> shift.
![shiftsetup](https://github.com/dhanasingh/redmine_wktime/assets/20320262/c7ac7bfc-a479-49b3-97e3-2a051a6a3554)

**Comment by Raw1mage** [comment]
Thanks, cdhaha, 
Just followed your directions and found the setting.

Just wondering that the leave types are not designed as my  imagination.
It seems that the leave types are hard associated to currently issues enlisted under projects, not "sick leave", "annual leave", "maternity leave", etc. as we commonly expected.  

Sounds easy to solve, I have to create a leaving project and create all the leave types as issues.
