### ISSUE TITLE
It would be nice to have a dashboard showing currently clocked-in team members

### ISSUE THREAD

**Issue by Raw1mage** [dhanasingh/redmine_wktime#295]
Just an idea sharing.
Since I appreciate this plugin very much, 
and the team usually works together remotely,
so I'd desire a dashboard showing the presency of the team members, 
based on the HR attendance module.

Thanks.

**Comment by cdhana17** [comment]
There is already a chart for clock in users, you can click on it to get details
<img width="1422" alt="clockin dashboard" src="https://github.com/dhanasingh/redmine_wktime/assets/20320262/e30b3e33-3ca3-4c7a-8511-ab0a5a671601">
Also you can see who has clocked in using the 'show on map' feature
<img width="1428" alt="clockin map" src="https://github.com/dhanasingh/redmine_wktime/assets/20320262/085c0beb-e683-458c-9bd6-d1633d7a06f9">
Does these suffice your needs ? or do you have something else in mind ?

**Comment by Raw1mage** [comment]
cool.
I'd have a try.
