### ISSUE TITLE
Confliction with redmine_dmsf plugin

### ISSUE THREAD

**Issue by Raw1mage** [dhanasingh/redmine_wktime#296]
Dear dev.
I hope this info helps the development.

https://github.com/danmunn/redmine_dmsf/issues/1468#issue-186061236

**Comment by cdhana17** [comment]
We will take a look.

**Comment by jmtemmos** [comment]
Hello all. I have exactly the same problem, and will have to choose from these two excellent plugins unfortunately....

**Comment by jmtemmos** [comment]
> We will take a look.

Hello, any update on this one ?

Thanks

**Comment by cdhana17** [comment]
This issue is fixed in 4.7.1. 
4.7.1 is released, Please take a look.

Thanks 
Dhanalakshmi

**Comment by jmtemmos** [comment]
Thanks a lot. I confirm it's working. Great job :)
