### ISSUE TITLE
Can't edit clock-in/clock-out values

### ISSUE THREAD

**Issue by yzenezy** [dhanasingh/redmine_wktime#297]
Version 4.7
Redmine 5.0.5
Ruby 3.0.0

Can't edit clock-in/clock-out values.

The user is has All Permissions enabled:

![image](https://github.com/dhanasingh/redmine_wktime/assets/14084092/66902a60-9f02-48d3-9c8c-65a180c14c23)

Can click the pencil in the 'clock-in' column:
![image](https://github.com/dhanasingh/redmine_wktime/assets/14084092/2b038c3d-b1e5-4240-bc88-4bee854ac9f8)

But can't edit anything:
![image](https://github.com/dhanasingh/redmine_wktime/assets/14084092/8ecf01a6-dad1-4340-b5d5-89770826cd24)

Can click the pencil for each row:
![image](https://github.com/dhanasingh/redmine_wktime/assets/14084092/4be64c94-5b20-457e-a957-0a94b7832ce5)

But all the fields are locked?
![image](https://github.com/dhanasingh/redmine_wktime/assets/14084092/2b2b2d4b-0091-49ba-b742-6a6dc51a6e60)

Expectation is that editing will work but no editing is possible.

Can you please assist?

Thanks in advance.

Kind regards,
Tom

**Comment by cdhana17** [comment]
Hi,
A user cannot edit their own clock in/out entry even if they have all permissions.

**Comment by yzenezy** [comment]
Hi cdhana17,

Thank you for that.

So I understand that a user can't edit their own clock i/out times.

Now I see that an ERPmine admin can edit the times of another user  but the changes don't save.

As **redmine root** I can't edit another user's (Tom Robinson) clock in/out.

![screenshot_20230906083844](https://github.com/dhanasingh/redmine_wktime/assets/14084092/30b1063c-1670-4f10-8bcd-f443211fea10)

![screenshot_20230906075631](https://github.com/dhanasingh/redmine_wktime/assets/14084092/9f6ad938-2fa4-438e-b120-3c8e15ee56e6)

Start and end times have reverted to original values. What is **remaining hours** meant to represent?
![screenshot_20230906075729](https://github.com/dhanasingh/redmine_wktime/assets/14084092/5d204d76-dd1c-405b-94d7-0506d2f081cc)

Expected changes aren't saved.  Something changed but really not sure why or what's happening here:
![screenshot_20230906075838](https://github.com/dhanasingh/redmine_wktime/assets/14084092/75b08bcb-f0cf-44be-afb1-b45cc1920a21)

After clicking **Save and continue** all values revert. Message in green is **Nothing to Save**
![screenshot_20230906080003](https://github.com/dhanasingh/redmine_wktime/assets/14084092/7ef55a8d-c49b-4de7-a015-b1697f7d8183)

**Comment by cdhana17** [comment]
ok, we will fix it in the next release

Thanks
Dhanalakshmi

**Comment by cdhana17** [comment]
This issue is fixed in 4.7.1. 
4.7.1 is released, Please take a look.

Thanks 
Dhanalakshmi
