### ISSUE TITLE
Under IE doesn't save corrient hours

### ISSUE THREAD

**Issue by dima21m** [dhanasingh/redmine_wktime#31]
Hi
Under IE the plugin save in the table 'wktime' field 'hours' 0 hours when I save my new Timesheet.
In the log:
Current user: dima21m (id=4)
  Rendered plugins/redmine_wktime/app/views/wktime/_wktime_cf_in_row.erb (0.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_issues2.html.erb (15.3ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (2.3ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_row_template.html.erb (17.9ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_header.html.erb (1.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_wktime_cf_in_row_header.html.erb (0.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_issue_header.html.erb (1.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_wktime_cf_in_row.erb (0.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_issues2.html.erb (12.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (1.5ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_wktime_cf_in_row.erb (0.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_issues2.html.erb (11.5ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (1.8ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_wktime_cf_in_row.erb (0.0ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_issues2.html.erb (11.7ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.0ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (1.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_wktime_cf_in_row.erb (0.1ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_issues2.html.erb (10.3ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.7ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (0.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_hours.html.erb (1.3ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_issues.html.erb (73.2ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_edit_footer.html.erb (2.6ms)
  Rendered plugins/redmine_wktime/app/views/wktime/edit.html.erb within layouts/base (98.8ms)
Completed 200 OK in 372ms (Views: 113.5ms | ActiveRecord: 78.4ms)
Started POST "/redmine/wktime/update" for 10.0.27.47 at 2015-07-23 12:42:40 +0300
Processing by WktimeController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"lWzZPzdCOzit97qda6Akuqg08CgNAG0ND1NBOL/b0w3rnChX/YXf/7Driui3zd0tlW5RU9Dd8iR9SFEQg1u51Q==", "tab"=>"wktime", "back_url"=>"http://redmine-rti.rt.ru:8081/redmine/wktime/index?tab=wktime", "getissues_url"=>"/redmine/wktime/getissues", "getactivities_url"=>"/redmine/wktime/getactivities", "deleterow_url"=>"/redmine/wktime/deleterow", "user_id"=>"13", "startday"=>"2015-07-27", "time_entry"=>[{"project_id"=>"15", "issue_id"=>"190", "activity_id"=>"99", "comments"=>""}, {"project_id"=>"24", "issue_id"=>"186", "activity_id"=>"99", "comments"=>""}, {"project_id"=>"77", "issue_id"=>"471", "activity_id"=>"99", "comments"=>""}, {"project_id"=>"77", "issue_id"=>"472", "activity_id"=>"99", "comments"=>""}], "hours1"=>["5", "", "", "", "", "", ""], "ids1"=>["", "", "", "", "", "", ""], "disabled1"=>["false", "false", "false", "false", "false", "false", "false"], "hours2"=>["", "6", "", "", "", "", ""], "ids2"=>["", "", "", "", "", "", ""], "disabled2"=>["false", "false", "false", "false", "false", "false", "false"], "hours3"=>["", "", "4", "", "4", "", ""], "ids3"=>["", "", "", "", "", "", ""], "disabled3"=>["false", "false", "false", "false", "false", "false", "false"], "hours4"=>["", "", "", "6", "", "", ""], "ids4"=>["", "", "", "", "", "", ""], "disabled4"=>["false", "false", "false", "false", "false", "false", "false"], "total"=>"0.00", "unit"=>"", "wktime_save"=>"Сохранить"}
  Current user: dima21m (id=4)

**Comment by dima21m** [comment]
IE doesn't recalculate thours and @total_hours when I type number in hours cells in my timesheet

**Comment by dima21m** [comment]
![ts_error](https://cloud.githubusercontent.com/assets/11782383/8851440/23de79fa-3158-11e5-8da5-24f7094f6eb9.jpg)
lmage

**Comment by dhanasingh** [comment]
do you still have this problem.
what version of IE, Redmine and ERPmine do you have ?

**Comment by CSCSxx** [comment]
I think this thread can be closed, especially since IE 11 is EOL from June 2022
