### ISSUE TITLE
Does Time & Expense 1.9 work with the latest redmine 3.1.0

### ISSUE THREAD

**Issue by SFDCACE** [dhanasingh/redmine_wktime#32]
I installed the plugin on the 3.1.0 version, however, my server is not opening now.
Below are the logs:

Started GET "/" for 127.4.161.1 at 2015-09-08 12:58:09 -0400
Processing by WelcomeController#index as HTML
  Current user: xxxxxx
  Rendered welcome/index.html.erb within layouts/base (5.8ms)
Completed 500 Internal Server Error in 22ms (ActiveRecord: 2.7ms)

ActionView::Template::Error (uninitialized constant WktimeHelper):
    22: <div id="top-menu">
    23:     <div id="account">
    24:         <%= render_menu :account_menu -%>
    25:     </div>
    26:     <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
    27:     <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
    28: </div>
  lib/redmine/menu_manager.rb:446:in `call'
  lib/redmine/menu_manager.rb:446:in `allowed?'
  lib/redmine/menu_manager.rb:164:in `block in menu_items_for'
  lib/redmine/menu_manager.rb:163:in `each'
  lib/redmine/menu_manager.rb:163:in `menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  app/views/layouts/base.html.erb:25:in `_app_views_layouts_base_html_erb__1004986979072748978_32673980'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Please advise/suggest.

**Comment by suganya-thulasiraman** [comment]
We have not tested fully Time & Expense 1.9 with Redmine 3.1.0 but Time & Expense 1.9 is compatible with Redmine 3.0.1

**Comment by Catlon** [comment]
Same problem here...
Have you found a way around this?

**Comment by suganya-thulasiraman** [comment]
Latest release Time & Expense 2.0 is compatible with Redmine 3.1.0

**Comment by Catlon** [comment]
I understand, but i'm getting the same error @SFDCACE mentioned on a vanilla install.
Could you help us sort this issue out? I'm pretty new to Redmine so i'd appreciate the help.
Best,
C.

**Comment by dhanasingh** [comment]
Are you also trying to install Time & Expense 1.9 on Redline 3.1 ?

**Comment by Catlon** [comment]
Yes absolutely. Can you help me out ?

**Comment by suganya-thulasiraman** [comment]
Since Time & Expense 1.9 is not compatible with Redmine 3.1.0, you will have to go to either Time & Expense 2.0 if you want Redmine 3.1.0 Otherwise get Redmine 3.0.1 if you want Time & Expense 1.9.
Can you please make the changes and let us know you feedback.

**Comment by suganya-thulasiraman** [comment]
Time & Expense 2.0 is compatible with Redmine 3.1.0
