### ISSUE TITLE
v1.9: err 500 undefined method `join' for "all":String

### ISSUE THREAD

**Issue by ste26054** [dhanasingh/redmine_wktime#33]
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    development
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem  
Redmine plugins:
  redmine_admin_monitor          1.0.0
  redmine_agile                  1.3.8
  redmine_custom_workflows       0.1.3
  redmine_draw_erd               0.1.0
  redmine_evm                    1.0.0
  redmine_graphs                 0.0.1
  redmine_importer               1.2.2
  redmine_leaves_holidays        0.1
  redmine_local_avatars          0.2.0
  redmine_logs                   0.0.5
  redmine_subtasks_inherited_fields 0.0.3
  redmine_timesheet_importer     0.1
  redmine_wktime                 1.9
  redmine_workload_capacity      0.0.1
  spectator                      0.0.1

Message: undefined method `join' for "all":String

Params:
controller: wktime
action: index

Backtrace:
/usr/share/redmine/plugins/redmine_wktime/app/controllers/wktime_controller.rb:1404:in `getWhereCond'
/usr/share/redmine/plugins/redmine_wktime/app/controllers/wktime_controller.rb:1381:in`findBySql'
/usr/share/redmine/plugins/redmine_wktime/app/controllers/wktime_controller.rb:98:in `index'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in`send_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in`process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in`call'

**Comment by suganya-thulasiraman** [comment]
This could be a browser cache issue. Could you please clear the browser cache and try again.

**Comment by ste26054** [comment]
The issue is still present after clearing the cache. I have also cleared the wk tables.

**Comment by dhanasingh** [comment]
this could be a compatibility issue
wktime 1.9 is compatible with Redmine 3.0
wktime 2.0 is compatible with Redmine 3.1

Can you try the right versions and see if it works fine for you
