### ISSUE TITLE
Error on RM 3.1.1 with MS SQL 2014 database

### ISSUE THREAD

**Issue by Meindert66** [dhanasingh/redmine_wktime#35]
I’m on MS SQL server 2014 in combination with redmine 3.1.1
 
Selecting the plugin button “Time & Expense” from the browser in redmine results in:
 
….
 
ActiveRecord::StatementInvalid (TinyTds::Error: 'date' is not a recognized built-in function name.: EXEC sp_executesql N'select count(*) as id from (select tmp3.user_id, tmp3.spent_on, tmp3.hours, tmp3.status, tmp3.status_updater, tmp3.created_on from (select tmp1.id as user_id, tmp1.created_on, tmp1.selected_date as spent_on, case when tmp2.hours is null then 0 else tmp2.hours end as hours, case when tmp2.status is null then ''e'' else tmp2.status end as status, tmp2.status_updater from (select u.id, u.created_on, v.selected_date from (select DateAdd(d, t4.i*7*10000 + t3.i*7*1000 + t2.i*7*100 + t1.i*7*10 + t0.i*7,''2015-11-01'') selected_date from (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t0, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t1, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t2, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t3, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t4) v, (select u.id, u.created_on from users u) u  WHERE  v.selected_date between ''2015-11-01'' and ''2015-12-05'' ) tmp1 left join (select v1.user_id, v1.startday as spent_on, v1.hours, case when w.status is null then ''n'' else w.status end as status , un.firstname + '' '' + un.lastname as status_updater  from (select  ROW_NUMBER() OVER (ORDER BY  DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on) desc, user_id) AS rownum,DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on) as startday,  t.user_id, sum(t.hours) as hours ,max(t.id) as id from time_entries t, users u where u.id = t.user_id and u.id in (9) and t.spent_on between ''2015-11-01'' and ''2015-12-05'' group by DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on), user_id ) as v1 left outer join wktimes w on v1.startday = w.begin_date and v1.user_id = w.user_id left outer join users un on un.id = w.statusupdater_id) tmp2 on tmp1.id = tmp2.user_id and tmp1.selected_date = tmp2.spent_on where tmp1.id in (9) ) tmp3  left outer join (select min( DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on) ) as min_spent_on, t.user_id as usrid from time_entries t, users u  where u.id = t.user_id and u.id in (9) group by t.user_id ) vw on vw.usrid = tmp3.user_id WHERE ((tmp3.spent_on between case when vw.min_spent_on is null then DateAdd(d, (((((DATEPART(dw,date(tmp3.created_on))-1)%7)-1)+(8-0)) % 7)*-1,date(tmp3.created_on)) else vw.min_spent_on end and ''2015-11-07'') OR ((tmp3.spent_on < case when vw.min_spent_on is null then DateAdd(d, (((((DATEPART(dw,date(tmp3.created_on))-1)%7)-1)+(8-0)) % 7)*-1,date(tmp3.created_on)) else vw.min_spent_on end and tmp3.status <> ''e'') OR (tmp3.spent_on > ''2015-11-07'' and tmp3.status <> ''e'')))  order by tmp3.spent_on desc, tmp3.user_id ) as v2'):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 
….

**Comment by Meindert66** [comment]
I guess its the date(tmp3.created_on) 

could this be a solution ?  CAST(tmp3.created_on AS DATE)

**Comment by Meindert66** [comment]
After I make a patch on the date cast the following error appears:

TinyTds::Error: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.: EXEC sp_executesql N'select count(*) as id from (select tmp3.user_id, tmp3.spent_on, tmp3.hours, tmp3.status, tmp3.status_updater, tmp3.created_on from (select tmp1.id as user_id, tmp1.created_on, tmp1.selected_date as spent_on, case when tmp2.hours is null then 0 else tmp2.hours end as hours, case when tmp2.status is null then ''e'' else tmp2.status end as status, tmp2.status_updater from (select u.id, u.created_on, v.selected_date from (select DateAdd(d, t4.i*7*10000 + t3.i*7*1000 + t2.i*7*100 + t1.i*7*10 + t0.i*7,''2015-11-01'') selected_date from (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t0, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t1, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t2, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t3, (select 0 i union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t4) v, (select u.id, u.created_on from users u) u  WHERE  v.selected_date between ''2015-11-01'' and ''2015-12-05'' ) tmp1 left join (select v1.user_id, v1.startday as spent_on, v1.hours, case when w.status is null then ''n'' else w.status end as status , un.firstname + '' '' + un.lastname as status_updater  from (select  ROW_NUMBER() OVER (ORDER BY  DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on) desc, user_id) AS rownum,DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on) as startday,  t.user_id, sum(t.hours) as hours ,max(t.id) as id from time_entries t, users u where u.id = t.user_id and u.id in (-1) and t.spent_on between ''2015-11-01'' and ''2015-12-05'' group by DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on), user_id ) as v1 left outer join wktimes w on v1.startday = w.begin_date and v1.user_id = w.user_id left outer join users un on un.id = w.statusupdater_id) tmp2 on tmp1.id = tmp2.user_id and tmp1.selected_date = tmp2.spent_on where tmp1.id in (-1) ) tmp3  left outer join (select min( DateAdd(d, (((((DATEPART(dw,t.spent_on)-1)%7)-1)+(8-0)) % 7)*-1,t.spent_on) ) as min_spent_on, t.user_id as usrid from time_entries t, users u  where u.id = t.user_id and u.id in (-1) group by t.user_id ) vw on vw.usrid = tmp3.user_id WHERE ((tmp3.spent_on between case when vw.min_spent_on is null then DateAdd(d, (((((DATEPART(dw,CAST(tmp3.created_on AS date))-1)%7)-1)+(8-0)) % 7)*-1,CAST(tmp3.created_on AS date)) else vw.min_spent_on end and ''2015-11-07'') OR ((tmp3.spent_on < case when vw.min_spent_on is null then DateAdd(d, (((((DATEPART(dw,CAST(tmp3.created_on AS Date))-1)%7)-1)+(8-0)) % 7)*-1,CAST(tmp3.created_on AS Date)) else vw.min_spent_on end and tmp3.status <> ''e'') OR (tmp3.spent_on > ''2015-11-07'' and tmp3.status <> ''e'')))  order by tmp3.spent_on desc, tmp3.user_id ) as v2'
Completed 500 Internal Server Error in 185ms (ActiveRecord: 101.0ms)

**Comment by Meindert66** [comment]
Did this plugin working in MS SQL server ?

**Comment by suganya-thulasiraman** [comment]
I think, there are some issues with the combination of Time & Expense 2.0 and MS SQL Server.
We are looking into it. Will fix it in the future release.

**Comment by suganya-thulasiraman** [comment]
Fixed in Time & Attendance 2.1.1
