### ISSUE TITLE
LoadError: cannot load such file -- rufus/scheduler

### ISSUE THREAD

**Issue by kristofer55** [dhanasingh/redmine_wktime#39]
Hello, i have a problem to restore database redmine bitnami 3.2.0.1.
During database migration I have error:

DL is deprecated, please use Fiddle
rake aborted!+
_LoadError: cannot load such file -- rufus/scheduler_+
C:/Bitnami/redmine-3.2.0-1/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/act
ivesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
C:/Bitnami/redmine-3.2.0-1/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/act
ivesupport-4.2.5/lib/active_support/dependencies.rb:274:in`block in require'
C:/Bitnami/redmine-3.2.0-1/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/act
ivesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
C:/Bitnami/redmine-3.2.0-1/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/act
ivesupport-4.2.5/lib/active_support/dependencies.rb:274:in`require'
C:/Bitnami/redmine-3.2.0-1/apps/redmine/htdocs/plugins/redmine_wktime/init.rb:20
6:in `block in <top (required)>'

Can any body help me?

**Comment by dhanasingh** [comment]
We are not familiar with bitnami installations, please see if this forum item would help https://www.redmine.org/boards/3/topics/35683?r=35684#message-35684

**Comment by kristofer55** [comment]
I describe from the beginning what I did.
1. Backup 2.6.9 redmine database without plugin wk_time
2. Installation 3.2.0 redmine
a) Restore database
b) Install Plugin wk_time without rufus-scheduler
c) Migration: ruby ​​bin / rake db: migrate RAILS_ENV = production - OK!
d) Migration: ruby ​​bin / rake redmine: plugins RAILS_ENV = production - OK!
Restart Redmine ... and it works.

The second restart after two days and redmine does not work. After removing the plugin wk_time - redmine works.
I thought that something was wrong so I installed tries again
3) Backup database redmine 3.2.0
4) Once again, the installation redmine 3.2.0 and the new restoration database redmine 3.2.0
a) Migration: ruby ​​bin / rake db: migrate RAILS_ENV = production - error LoadError: can not load a dry file - Rufus / scheduler
b) Migration: ruby ​​bin / rake redmine: plugins RAILS_ENV = production - error LoadError: can not load a dry file - Rufus / scheduler

I read that You write there must be install:
1) gem install rufus-scheduler, something else must be configured after installation?
2) Configuration apache?
a) 1 PassengerMinInstances
b) RailsAppSpawnerIdleTime 0
c) PassengerPreStart
What is the configuration file?
apache2 \ conf \ original \ httpd.conf?

I'm begginer in redmine confguration and will be glad for your help :)

**Comment by kristofer55** [comment]
any idea ?

**Comment by dhanasingh** [comment]
we have not tested with bitnami insulations, check out the link I posted in my previous message, might be useful.
no rufus scheduler configuration is required.
mostly httpd.conf is the apache configuration file, but some installations might have it differently

**Comment by quynhnv123** [comment]
I got similar issue with the following step
1. Install wk_time plugin in Bitnami Redmine 3.3.0-1 and configure wk_time successfully
2. Restart the server then redmine doesnt start
Please help to fix this issue

**Comment by quynhnv123** [comment]
Already have solution for this issue with the following step:
1. Run: bundle install
2. Run: bundle install --no-deployment
3. Re-install wk_time plugin: bundle exec rake redmine:plugins:migrate RAILS_ENV=production
