### ISSUE TITLE
Sending reminder emails to blocked users

### ISSUE THREAD

**Issue by jhlaveau** [dhanasingh/redmine_wktime#43]
**Synopsis : 
When using the "Send email for non submission" function, Redmine blocked users are receiving emails whereas they do not have access to Redmine any more. 
**Solution :
In file wktime_helper.rb, line 612, change the line : 
	`	" inner join users u on m.user_id = u.id" +`
by 
`		" inner join users u on m.user_id = u.id and u.status = #{User::STATUS_ACTIVE}" +`
Thank you for taking this request into account
Best regards 
Jean-Hervé

**Comment by jupsoleil** [comment]
I can confirm that locked users receive mails while they shouldn't.
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.1.1

**Comment by suganya-thulasiraman** [comment]
Fixed in 2.1.2

**Comment by jupsoleil** [comment]
Confirmed fixed. Please close.
