### ISSUE TITLE
Expense logo configuration

### ISSUE THREAD

**Issue by jupsoleil** [dhanasingh/redmine_wktime#47]
Hello, it would be nice to add to the manual that a custom logo to be used for expense export to pdf needs to be stored in $(REDMINEROOT)/public/plugin_assets/redmine_wktime/images .
It would be nicer still to make line 203 (wktime_helper.rb) use values configured through the plugin's settings, so that a custom logo doesn't appear to be stretched if not having the same aspect ratio as the default logo:
pdf.Image(Redmine::Plugin.public_directory + "/redmine_wktime/images/" + logo, page_width-50, 10,40,25)
If you desire so, I could make an attempt of changing the code myself, but at present I don't master ruby, so it might not be very wise.
Thanks!
(version 2.1.1)

**Comment by suganya-thulasiraman** [comment]
We have updated the Time & Attendance user guide with information for logo configuration.

**Comment by jupsoleil** [comment]
Thanks for your efforts, but on http://www.adhisoftware.co.in/products/time-attendance/ ; http://www.adhisoftware.co.in/wp-content/uploads/TE-User-Guide.pdf I cannot see the updated user manual yet.  Could you please give me the (new) link?

**Comment by dhanasingh** [comment]
sorry, the document is updated now
