### ISSUE TITLE
Use Detail Time Entry Popup not showing

### ISSUE THREAD

**Issue by jupsoleil** [dhanasingh/redmine_wktime#48]
Hello, it seems the detail entry popup doesn't work anymore even if configured to show up in redmine/settings/plugin/redmine_wktime.

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.1.1

**Comment by suganya-thulasiraman** [comment]
Do you have custom fields configured for spent time?

**Comment by jupsoleil** [comment]
No, no custom fields.

**Comment by suganya-thulasiraman** [comment]
What about comments? Do you have "Enter Comment in row" checked? If you have it checked, then detail time entry popup won't show up.

**Comment by jupsoleil** [comment]
Interesting, indeed, it seems you cannot both enter it in row and as detail.  Would it then not be better to have this selectable from a drop-down with these two options?

**Comment by suganya-thulasiraman** [comment]
Yes, you cannot have comments both in row and in detail popup. 
Time Entry Popup shows both comments and custom fields, but the change you propose is only applicable for comments.

**Comment by jupsoleil** [comment]
OK, fine for me :-).
