### ISSUE TITLE
Timesheet submission reminder mail is sent to all users (or so it seems)

### ISSUE THREAD

**Issue by jupsoleil** [dhanasingh/redmine_wktime#49]
Hello, users who don't have the right to log spent time are sent a reminder mail to submit their timesheets.
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.1.1

**Comment by suganya-thulasiraman** [comment]
Could you please check whether the user have log time permission in any of the assigned projects.

**Comment by jupsoleil** [comment]
Indeed, it was a bad configuration from my side!  Sorry for that.
