### ISSUE TITLE
Decimals are not taken into account when registering expenses

### ISSUE THREAD

**Issue by jupsoleil** [dhanasingh/redmine_wktime#50]
Hello, on my installation, expense values of e.g. 84.75€ are registered as 84.00€ after submit.
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_wktime                 2.1.1

**Comment by jupsoleil** [comment]
Excuse me, did you find time to look into this?

**Comment by suganya-thulasiraman** [comment]
Yes, we have verified it as a bug. Will fix it in the next release.

**Comment by suganya-thulasiraman** [comment]
Fixed in 2.1.2 and it is released

**Comment by jupsoleil** [comment]
Thanks, working!
