### ISSUE TITLE
checkViewPermission undefined on upgrading

### ISSUE THREAD

**Issue by ahnkle** [dhanasingh/redmine_wktime#55]
I was running redmine 2.3.2 with wktime (v1.2 I think, according to init.rb). This was _not_ using bitnami.

I upgraded to bitnami redmine 2.6.10-2, and used got clone to get the updated plugin. This is on Ubuntu 14.04.

Now I get the error below only when wktime is present.

> Started GET "/redmine/" for 192.168.0.104 at 2016-05-09 10:39:41 +0100
> Processing by WelcomeController#index as HTML
>   Current user: jeremy (id=3)
>   Rendered news/_news.html.erb (7.0ms)
>   Rendered welcome/index.html.erb within layouts/base (47.5ms)
> Completed 500 Internal Server Error in 121.4ms
> 
> ActionView::Template::Error (undefined method `checkViewPermission' for #<Object:0x007fc31d1949b0>):
>     23: <div id="top-menu">
>     24:     <div id="account">
>     25:         <%= render_menu :account_menu -%>
>     26:     </div>
>     27:     <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.
> logged? %>
>     28:     <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
>     29: </div>
>   lib/redmine/menu_manager.rb:199:in`call'
>   lib/redmine/menu_manager.rb:199:in `allowed_node?'
>   lib/redmine/menu_manager.rb:166:in`block in menu_items_for'
>   lib/redmine/menu_manager.rb:165:in `each'
>   lib/redmine/menu_manager.rb:165:in`menu_items_for'
>   lib/redmine/menu_manager.rb:90:in `render_menu'
>   app/views/layouts/base.html.erb:26:in`_app_views_layouts_base_html_erb__2319392326662076436_70238146978620'

**Comment by dhanasingh** [comment]
so you are using redmine 2.6 ? and what version of Time & Attendance plugin are you using ?

**Comment by dhanasingh** [comment]
no response, hence closing it
