### ISSUE TITLE
Edit Attendance Time

### ISSUE THREAD

**Issue by schitzN** [dhanasingh/redmine_wktime#57]
Hey there dhanasingh,

we really love your plugin!

Is there a way to edit the attendance time directly in the Time -> Week Overview? We do not want to use the stopwatch to track time, instead we want to directly write start & end time. There is even this small pop-up showing all logged times, but unfortunatelly, these fields are also not editable.

Are we missing something?

**Comment by dhanasingh** [comment]
thanks for your feedback, can you please rate the Time & Attendance plugin on redline site when you get a chance https://www.redmine.org/plugins/wk-time

Currently the clocked in times are editable only to TE-Admins, did you try it as TE-Admin ?

**Comment by schitzN** [comment]
Thanks @dhanasingh for your fast response!

i tried with redmine-admin and multiple users, nothing works... alle these fields are grayed out.
Or what do you mean with TE-Admin?

**Comment by dhanasingh** [comment]
You can configure a user group as TE-Admin, please check out the plugin configurations

**Comment by schitzN** [comment]
Okay it's working now!

The problem was, that we activated the approval system and then the clocked times are not editable anymore - even TE admins are not capable of it anymore.

**Comment by karthickmadhiazhagan** [comment]
I don't think the approval system has any impact on the attendance time, A TE Admin cannot edit his own timings, but can edit others, can you send us a screenshot ?
