### ISSUE TITLE
Attendance Time - Start Time

### ISSUE THREAD

**Issue by schitzN** [dhanasingh/redmine_wktime#60]
Hey @dhanasingh 

sry for opening the fourth issue in this short time - we are currently testing everything, because we really would like to use your plugin in production!

So we are now tracking time by adding the time directly in the overview. The problem is, that as soon as we have more than one timespan on one day, the start time of my attendance only shows the start-time of the last timespan.

Example:
i'm working today from 8:00 - 12:00 and then from 13:00 - 17:00. This means, there are two timespans now. The total time is correct - 8 hours in total - but the start time now shows 13:00, the start-time of the latest tracked timespan!

**Comment by dhanasingh** [comment]
Did you open the detail pop up ? You will see all timespans there

**Comment by schitzN** [comment]
Yes, i saw the detail pop up - but the overview is still wrong.

The thing is, we consider printing this overview-page while the pdf-generation does not include attendance times and then we need the correct start and end  time of the day's attendance!

**Comment by dhanasingh** [comment]
It puts the last timespan, you want the first timespan ?

**Comment by schitzN** [comment]
No, in my opinion, this overview should show the Start of the first tracked timespan of the day as Start and the End of the last tracked timespan of the day as End.

So to take the example from above, with 2 tracked timespans (8:00 - 12:00 and 13:00 - 17:00) it should show 8:00 - 17:00 (8h).

**Comment by dhanasingh** [comment]
Ok, we will put that in

**Comment by schitzN** [comment]
hey, very n1, thank you very much! :+1:

**Comment by karthickmadhiazhagan** [comment]
We have completed this in 2.2.1 and it is released.
