### ISSUE TITLE
wkstatus.js:98 Uncaught TypeError is causing "Loading..." not dismissed

### ISSUE THREAD

**Issue by jza0330** [dhanasingh/redmine_wktime#63]
In case time tracking module is not enabled for the redmine project and you simply view the issue then "Loading..." does not disappear. Please see attached screenshot. In browser console you can see error
_wkstatus.js:98 Uncaught TypeError: Cannot set property 'disabled' of null_
Additional Note: This behavior can be also achieved when you disable Time tracking activities for the role
### Environment
- Lets have project X
- Redmine 3.3.0
- Chrome Version 51.0.2704.106 m or IE 11.494.10586.0
- redmine_wktime 2.2.1
### Steps to reproduce:
1. Go to Project Setting of project X-->Modules and disable here time tracking module
2. Go to project X and click Issues
3. Choose one issue
4. You should see "Loading..."
### Screens:

**Console Error:**
![console](https://cloud.githubusercontent.com/assets/12050752/16944890/e0ce38ea-4da2-11e6-8a66-600fd5c329fc.png)
**Issue view with Loading...:**
![loading](https://cloud.githubusercontent.com/assets/12050752/16944891/e0d1b358-4da2-11e6-90db-84f6b80cab16.png)
**How to disable time tracking:**
![timetracking disabled](https://cloud.githubusercontent.com/assets/12050752/16945059/cdb312f2-4da3-11e6-85f9-c0b7e2b6e194.png)

**Comment by BRUTEF0RCE** [comment]
I do have the same problem.  Any suggested fix for this?

**Comment by karthickmadhiazhagan** [comment]
Hi,
We have fixed this in the development. We should see in the next release.

Thanks,
Karthick

**Comment by BRUTEF0RCE** [comment]
Thank you!! Cant wait for the next release! :)

**Comment by dhineshrajasekar** [comment]
Hi,
We have released ERPmine v2.7. Please take a look.

Thanks,
Dhineshkumar.R
