### ISSUE TITLE
Cannot access to Setting page

### ISSUE THREAD

**Issue by methys** [dhanasingh/redmine_wktime#65]
Hi all,

I just installed WKtime plugin on Redmine 3.1.1, the setting page is not accessible, it end with the following error, note that Attendance/Timesheet works fine :

 Rendered plugins/redmine_wktime/app/views/settings/_settings.html.erb (628.7ms)
  Rendered settings/plugin.html.erb within layouts/admin (631.1ms)
Completed 500 Internal Server Error in 642ms (ActiveRecord: 3.9ms)

ActionView::Template::Error (uninitialized constant WktimeHelper::Import):
    269:                <p style="margin-left: -180px;">
    270:                  <label><%= l(:setting_date_format) %></label>
    271:                  <% wktime_helper = Object.new.extend(WktimeHelper) %>
    272:                  <%= select_tag 'settings[wktime_field_datetime]', options_for_select(wktime_helper.date_format_options, :selected => @settings['wktime_field_datetime'].blank? ? 0 : @settings['wktime_field_datetime'] ) %>
    273:                </p>
    274:                <table>
    275:                <thead>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___4086189306586709232_69890579812760'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___4086189306586709232_69890579812760'
  app/helpers/application_helper.rb:322:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__4599062197108022927_69890579632800'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__4599062197108022927_69890579632800'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by karthickmadhiazhagan** [comment]
What version of Time & Attendance  you are using? 
If you are using T&A 2.3 then please upgrade your Redmine to 3.2 or greater version.
