### ISSUE TITLE
edit.js:575 Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by garethflowers** [dhanasingh/redmine_wktime#68]
In Time & Expenses - when using "Add Row" and then attempting to change the Project drop-down I am getting a type error `Cannot read property 'options' of undefined`. The screen is then stuck showing "Loading...".

![image](https://cloud.githubusercontent.com/assets/587323/18962336/55e02816-8668-11e6-9e36-9f75bd0fb1a4.png)

**Environment:**
- redmine 3.3
- redmine_wktime 2.4

**Comment by garethflowers** [comment]
After more testing it seems that this fault goes away once you enable the "Attendance Module" and the  "Clock In / Clock Out" feature. However this is not something we want to do.

![image](https://cloud.githubusercontent.com/assets/587323/18986629/950dc9de-86f5-11e6-943e-7f1a74b28267.png)

**Comment by dhineshrajasekar** [comment]
What browser version and OS you are testing? Could you clear your cache and try again.

**Comment by garethflowers** [comment]
Already tried clearing local browser cache and restarting server.

We are have tested on:
- Windows 10 using Chrome 53 and Edge.
- Windows 7 using Chrome 52.

You get the same problems on all machines.

**Comment by karthickmadhiazhagan** [comment]
We couldn't reproduce this issue in our environment .
We have tested it on Linux CentOS 6.6, MySQL 5.5.49, Redmine 3.3 and also in Windows 7,8 and 10, PostgreSQL 9.4.
Could you please provide us your server environment details.

**Comment by garethflowers** [comment]
We're using:
- Redmine 3.3, using Docker image `redmine:latest`
- Redmine Wktime 2.4
- PostgreSQL 9.1
- Windows 7 and 10
- Chrome (52, 53), Edge
