### ISSUE TITLE
The email notification is not sent

### ISSUE THREAD

**Issue by wallabom** [dhanasingh/redmine_wktime#7]
Hello,
after installing and configured the "	Send email for non submission ", we could see in Logs: 
==========Scheduler Started==========
Scheduler failed: uninitialized constant WktimeHelper::WkMailer

We then tested the rejected mail notification (sendRejectionEmail) that was not sent as well.

Nevertheless, the Redmine is sending successfully update notification.
It seems there is a misconfiguration on the plugin.
May you help please?
Thank you,
Greg

**Comment by dhanasingh** [comment]
I think there is a filename issue (case sensitive)
check this out 
http://www.redmine.org/boards/3/topics/39297?page=2

**Comment by wallabom** [comment]
The following change fixed the issue:
http://www.redmine.org/boards/3/topics/39297?r=45083#message-45083

Thank you for your help!
Regards,
Wall
