### ISSUE TITLE
Redmine is crashed when plugin removed

### ISSUE THREAD

**Issue by smartum-sv** [dhanasingh/redmine_wktime#71]
Started GET "/repositories/11/edit" for 127.0.0.1 at 2016-10-01 07:05:23 -0400
Processing by RepositoriesController#edit as HTML
  Parameters: {"id"=>"11"}
Settings cache cleared.
  Current user: sergey.valuy (id=4)
  Rendered repositories/_form.html.erb (31.8ms)
  Rendered repositories/edit.html.erb within layouts/base (40.3ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.6ms)
Completed 500 Internal Server Error in 827ms (ActiveRecord: 16.2ms)

ActionView::Template::Error (Missing partial wktime/_attendance_widget with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
- "/home/redmine/redmine-3.3.0/plugins/redmine_wktime/app/views"
- "/home/redmine/redmine-3.3.0/plugins/redmine_timesheet_plugin/app/views"
- "/home/redmine/redmine-3.3.0/plugins/redmine_mylyn_connector/app/views"
- "/home/redmine/redmine-3.3.0/plugins/redmine_contacts/app/views"
- "/home/redmine/redmine-3.3.0/plugins/redmine_checklists/app/views"
- "/home/redmine/redmine-3.3.0/plugins/redmine_agile/app/views"
- "/home/redmine/redmine-3.3.0/app/views"
  ):
  104:         <%= view_layouts_base_sidebar_hook_response %>
  105:     </div>
  106: 
  107:     <div id="content">
  108:         <%= render_flash_messages %>
  109:         <%= yield %>
  110:         <%= call_hook :view_layouts_base_content %>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in`map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:107:in`_app_views_layouts_base_html_erb__222549511432401199_69817129744040'
  app/controllers/application_controller.rb:488:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:486:in`render_error'
  app/controllers/application_controller.rb:474:in `render_404'
  app/controllers/application_controller.rb:498:in`missing_template'

**Comment by karthickmadhiazhagan** [comment]
Did you uninstall the T&A plugin properly as given in the README document?

**Comment by dhanasingh** [comment]
no response, hence closing it
