### ISSUE TITLE
I've error on repository page 

### ISSUE THREAD

**Issue by smartum-sv** [dhanasingh/redmine_wktime#72]
Started GET "/" for 127.0.0.1 at 2016-10-01 07:34:10 -0400
Processing by WelcomeController#index as HTML
Settings cache cleared.
  Current user: sergey (id=4)
  Rendered welcome/index.html.erb within layouts/base (21.4ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (10.2ms)
Completed 200 OK in 404ms (Views: 291.8ms | ActiveRecord: 12.1ms)
Started GET "/projects/seasme?jump=welcome" for 127.0.0.1 at 2016-10-01 07:34:17 -0400
Processing by ProjectsController#show as HTML
  Parameters: {"jump"=>"welcome", "id"=>"seasme"}
Settings cache cleared.
  Current user: sergey.valuy (id=4)
  Rendered plugins/redmine_contacts/app/views/projects/_contacts.html.erb (17.6ms)
  Rendered projects/_members_box.html.erb (8.9ms)
  Rendered projects/_sidebar.html.erb (10.2ms)
  Rendered projects/show.html.erb within layouts/base (120.3ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (14.3ms)
Completed 200 OK in 1395ms (Views: 967.5ms | ActiveRecord: 47.7ms)
Started GET "/projects/seasme/repository" for 127.0.0.1 at 2016-10-01 07:34:21 -0400
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"seasme"}
  Current user: sergey.valuy (id=4)
  Rendered common/error.html.erb within layouts/base (1.7ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (1.0ms)
Completed 404 Not Found in 446ms (Views: 133.9ms | ActiveRecord: 16.1ms)

**Comment by karthickmadhiazhagan** [comment]
Is this error cames after uninstall the T&A plugin?

**Comment by dhanasingh** [comment]
this may not be a erpmne plugin issue,, it could be a repository issue, hence closing it
