### ISSUE TITLE
error on 2.4

### ISSUE THREAD

**Issue by dima21m** [dhanasingh/redmine_wktime#73]
ActionView::Template::Error (uninitialized constant WktimeHelper::Import):
    273: 		<p style="padding-left: 130px;">
    274: 		  <label><%= l(:setting_date_format) %></label>
    275: 		  <% wktime_helper = Object.new.extend(WktimeHelper) %>
    276: 		  <%= select_tag 'settings[wktime_field_datetime]', options_for_select(wktime_helper.date_format_options, :selected => @settings['wktime_field_datetime'].blank? ? 0 : @settings['wktime_field_datetime'] ) %>
    277: 		</p>	
    278: 		<table>
    279: 		<thead>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___2076923091310901923_70368520158100'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___2076923091310901923_70368520158100'
  app/helpers/application_helper.rb:322:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___3413524833363526214_70368520079840'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___3413524833363526214_70368520079840'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by karthickmadhiazhagan** [comment]
Redmine Import works on Redmine 3.2 and greater version only. Please Upgrade your Redmine server and try again.

**Comment by dima21m** [comment]
OK, I will upgrade redmine from 3.1 to 3.3
