### ISSUE TITLE
No way to edit Public holidays

### ISSUE THREAD

**Issue by gitandrewkonovalov** [dhanasingh/redmine_wktime#74]
redmine_wktime 2.4

I looked through all settings and couldn't find a way to enter Public holidays. 

According to source code it should be a tab in settings and the list of Public holidays should be accessible via Setting.plugin_redmine_wktime['wktime_public_holiday']

**Comment by karthickmadhiazhagan** [comment]
From Time and Attendance 2.1 public holiday feature has moved into attendance module.
You have to create an issue called 'Public Holidays' and set that issue as leave in attendance tab in plugin configuration.
Then put time entry for that issue in Time sheet.

If you don't plan to use attendance module then please put log time for any issue.

**Comment by gitandrewkonovalov** [comment]
Does that mean I can't arrange Public holidays once per year (having a holiday calendar) so people don't have to enter hours for Public holidays manually?

**Comment by dhanasingh** [comment]
Are you using the min / max hour validation ? If you don't use the validation, you just don't log hours for those days

**Comment by danpfe** [comment]
Don't want to be negative, but the Public holidays as entered before was (at least to me), a bit more straight forward.

**Comment by dhanasingh** [comment]
Can you create the public holidays as a wiki page in a project.  May be you can include that page to the home page.  would that work ?

**Comment by dhanasingh** [comment]
Public Holidays feature is included in the Attendance Module of ERPmine 3.2.1, please take a look
