### ISSUE TITLE
ActionView::Template::Error (uninitialized constant WktimeHelper::Import):

### ISSUE THREAD

**Issue by Xo66uT** [dhanasingh/redmine_wktime#81]
When going to /settings/plugin/redmine_wktime
Trace
Started GET "/settings/plugin/redmine_wktime" at 2016-12-21 00:29:57 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_wktime"}
  Rendered plugins/redmine_wktime/app/views/settings/_tab_general.html.erb (0.8ms)
  Rendered plugins/redmine_wktime/app/views/settings/_tab_expense.html.erb (32.2ms)
  Rendered plugins/redmine_wktime/app/views/settings/_tab_approval.html.erb (4.3ms)
  Rendered plugins/redmine_wktime/app/views/settings/_tab_time.html.erb (46.3ms)
  Rendered plugins/redmine_wktime/app/views/settings/_tab_attendance.html.erb (734.9ms)
  Rendered common/_tabs.html.erb (784.7ms)
  Rendered plugins/redmine_wktime/app/views/settings/_settings.html.erb (785.7ms)
  Rendered settings/plugin.html.erb within layouts/admin (787.1ms)
Completed 500 Internal Server Error in 794ms (ActiveRecord: 9.6ms)

ActionView::Template::Error (uninitialized constant WktimeHelper::Import):
    273: 		<p style="padding-left: 130px;">
    274: 		  <label><%= l(:setting_date_format) %></label>
    275: 		  <% wktime_helper = Object.new.extend(WktimeHelper) %>
    276: 		  <%= select_tag 'settings[wktime_field_datetime]', options_for_select(wktime_helper.date_format_options, :selected => @settings['wktime_field_datetime'].blank? ? 0 : @settings['wktime_field_datetime'] ) %>
    277: 		</p>	
    278: 		<table>
    279: 		<thead>
  app/views/common/_tabs.html.erb:22:in `block in _48f3ac5c4b4652fc58aecab7694e22f4'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_48f3ac5c4b4652fc58aecab7694e22f4'
  app/helpers/application_helper.rb:322:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _55b7e196725b4e19671d85ed23a78db7'
  app/views/settings/plugin.html.erb:4:in `_55b7e196725b4e19671d85ed23a78db7'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by Xo66uT** [comment]
```
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            2.6.4
  Filesystem                     
  GitRemote                      2.6.4
Redmine plugins:
  advanced_roadmap_v2            2.4.3
  extended_fields                0.2.4
  extended_profile               1.2.1
  issue_charts                   1.3.0
  mega_calendar                  1.4.0
  redmine_base_deface            0.0.1
  redmine_bitbucket              1.0.0
  redmine_checklists             3.1.1
  redmine_contacts               4.0.4
  redmine_contacts_helpdesk      3.0.1
  redmine_git_remote             0.0.1
  redmine_issue_templates        0.1.0
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_coderay  0.2.0
  redmine_lightbox2              0.2.2
  redmine_multiprojects_issue    0.2
  redmine_people                 1.2.0
  redmine_slack                  0.1
  redmine_theme_changer          0.2.0
  redmine_wktime                 2.5.2
  redmine_zenedit                0.0.2
```

**Comment by karthickmadhiazhagan** [comment]
ERPmine 2.5.2 Compatible with Redmine 3.3.x. only. Please Upgrade your Redmine server and try again.

**Comment by Xo66uT** [comment]
Thanks for help. Upgrade to 3.3 resolve this problem.
