### ISSUE TITLE
can't enable Billing and accounting

### ISSUE THREAD

**Issue by demahom27** [dhanasingh/redmine_wktime#87]
I have the billing and the accounting features enabled on  the setting page, but they are not displayed on the plugin page?

I have redmine 3.3 and the plugin version is 2.6

**Comment by dhanasingh** [comment]
Do you have the billing user and admin group and the accounting user and admin group setup ?

**Comment by demahom27** [comment]
NO. I just set them up and it fixed the problem. Thank you.
