### ISSUE TITLE
Internal Error for Configuration

### ISSUE THREAD

**Issue by destiny931** [dhanasingh/redmine_wktime#89]
When I click configure within Administration/Plugins, I get 

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

I nstalled ERPmine 2.6 without any errors.  My Redmine version is 3.3.1-0.  Do you have any suggestions?

**Comment by dhanasingh** [comment]
Erpmine 2.6 was tested with 3.3.0 but it should work with 3.3.1, can you check the log for error details ?

**Comment by destiny931** [comment]
Are you referring to the production.log file located in redmine-3.3.1-0\apps\redmine\htdocs\log?

**Comment by destiny931** [comment]
Here is a portion of the production.log file.  I see the following 

 

Started GET "/redmine/settings/plugin/redmine_wktime" for 127.0.0.1 at 2017-01-25 12:47:52 -0500

Processing by SettingsController#plugin as HTML

  Parameters: {"id"=>"redmine_wktime"}

  Current user: atyus (id=5)

  Rendered plugins/redmine_wktime/app/views/settings/_tab_general.html.erb (4.0ms)

  Rendered common/_tabs.html.erb (7.0ms)

  Rendered plugins/redmine_wktime/app/views/settings/_settings.html.erb (8.0ms)

  Rendered settings/plugin.html.erb within layouts/admin (9.0ms)

Completed 500 Internal Server Error in 57ms (ActiveRecord: 42.0ms)

 

ActionView::Template::Error ("en - COPY" is not a valid locale):

    16:                      <% wkexpense_helper = Object.new.extend(WkexpenseHelper) %>

    17:                      <p>

    18:                                      <label><%= l(:label_wk_currency) %></label>

    19:                                      <%=h select_tag('settings[wktime_currency]',options_for_select(wkexpense_helper.options_for_currency,:selected => @settings['wktime_currency'])) %>

    20:                      </p>

    21:                      <p>

    22:                        <label><%= l(:label_wk_header_logo) %></label><%= text_field_tag 'settings[wktime_header_logo]', @settings['wktime_header_logo']%>

  lib/redmine/i18n.rb:58:in `ll'

**Comment by dhanasingh** [comment]
Thanks for the log, the log says you have a en-COPY, yml file in your locale, can you check that and remove it ?

**Comment by destiny931** [comment]
Thank you so much for your help.  You are the best!!! Your solution solved the problem.

**Comment by dhanasingh** [comment]
No problems you are welcome !

**Comment by destiny931** [comment]
Hi,

Is it possible to change the current logo that is displayed in the reports?  If so, can you give me instructions on how to?  Thank you

**Comment by dhanasingh** [comment]
Please place the logo file in redmine_wktime/assets/images folder

And set the file name for the header logo settings 

Then restart Redmine

**Comment by destiny931** [comment]
Thank you

**Comment by destiny931** [comment]
Hi,

I'm having trouble with uninstalling ERpmine.  I'm getting the following when trying to uninstall:


Errno::EACCES: Permission denied @ rb_sysopen - C:/Bitnami/redmine-3.3.1-0/apps/
redmine/htdocs/public/plugin_assets/redmine_wktime/images/Thumbs.db


 Any suggestions?

 

Output:


C:\Bitnami\redmine-3.3.1-0\apps\redmine\htdocs\plugins>bundle exec rake redmine:
plugins:migrate NAME=redmine_wktime VERSION=0 RAILS_ENV=production
(in C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs)
DL is deprecated, please use Fiddle
rake aborted!
Could not copy C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/plugins/redmine_wk
time/assets/images/Thumbs.db to C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/p
ublic/plugin_assets/redmine_wktime/images/Thumbs.db: Permission denied @ rb_syso
pen - C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/public/plugin_assets/redmin
e_wktime/images/Thumbs.db
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:417:in `res
cue in block in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:411:in `blo
ck in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `eac
h'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `mir
ror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:428:in `blo
ck in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:427:in `eac
h'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:427:in `mir
ror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/config/initializers/30-redmine.rb
:23:in `<top (required)>'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
(required)>'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Bitnami/redmine-3.3.1-0/apps/
redmine/htdocs/public/plugin_assets/redmine_wktime/images/Thumbs.db
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:414:in `blo
ck in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `eac
h'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `mir
ror_assets'

**Comment by destiny931** [comment]
Hi,

Let me explain the reason why I was trying to uninstall redmine_wrktime plugin.  A co-worker rebooted the machine that has redmine installed.  After the reboot, thin_redmine and thin_redmine2 did not start.   The production log showed 

 

[Tue Jan 31 10:55:57.700309 2017] [proxy:error] [pid 5324:tid 964] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s

[Tue Jan 31 10:55:57.700309 2017] [proxy_http:error] [pid 5324:tid 964] [client 192.168.0.105:54755] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://192.168.0.141:81/redmine

[Tue Jan 31 10:55:58.714311 2017] [proxy:error] [pid 5324:tid 964] (OS 10061)No connection could be made because the target machine actively refused it.  : AH00957: HTTP: attempt to connect to 127.0.0.1:3001 (127.0.0.1) failed

 

I then tried to uninstall plugin redmine_wrktime to see if it was causing the problem.  Than’s when I received 

 

Errno::EACCES: Permission denied @ rb_sysopen - C:/Bitnami/redmine-3.3.1-0/apps/
redmine/htdocs/public/plugin_assets/redmine_wktime/images/Thumbs.db

I deleted Thumbs.db from apps/redmine/htdocs/public/plugin_assets/redmine_wktime/images and I was able to start , thin_redmine and thin_redmine2.  So, now there’s no need to uninstall the plugin.

 

My question is…..  Why did the Permission denied problem occur?  What caused it?  Any idea?

 

Thanks,

April

 

 

 

From: April Tyus [mailto:destiny931@comcast.net] 
Sent: Tuesday, January 31, 2017 12:44 PM
To: dhanasingh/redmine_wktime <reply@reply.github.com>
Subject: Uninstall redmine_wrktime

 

Hi,

I'm having trouble with uninstalling ERpmine.  I'm getting the following when trying to uninstall:

 

Errno::EACCES: Permission denied @ rb_sysopen - C:/Bitnami/redmine-3.3.1-0/apps/
redmine/htdocs/public/plugin_assets/redmine_wktime/images/Thumbs.db

 

 Any suggestions?

 

Output:

 

C:\Bitnami\redmine-3.3.1-0\apps\redmine\htdocs\plugins>bundle exec rake redmine:
plugins:migrate NAME=redmine_wktime VERSION=0 RAILS_ENV=production
(in C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs)
DL is deprecated, please use Fiddle
rake aborted!
Could not copy C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/plugins/redmine_wk
time/assets/images/Thumbs.db to C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/p
ublic/plugin_assets/redmine_wktime/images/Thumbs.db: Permission denied @ rb_syso
pen - C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/public/plugin_assets/redmin
e_wktime/images/Thumbs.db
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:417:in `res
cue in block in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:411:in `blo
ck in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `eac
h'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `mir
ror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:428:in `blo
ck in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:427:in `eac
h'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:427:in `mir
ror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/config/initializers/30-redmine.rb
:23:in `<top (required)>'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
(required)>'
Errno::EACCES: Permission denied @ rb_sysopen - C:/Bitnami/redmine-3.3.1-0/apps/
redmine/htdocs/public/plugin_assets/redmine_wktime/images/Thumbs.db
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:414:in `blo
ck in mirror_assets'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `eac
h'
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:410:in `mir
ror_assets'

On January 30, 2017 at 4:25 PM April Tyus <destiny931@comcast.net <mailto:destiny931@comcast.net> > wrote:

Thank you

**Comment by dhanasingh** [comment]
don't know, may be some other process had the Thumbs.db locked
