### ISSUE TITLE
SettingsControllerPatch causes internal error on first access to other plugin's settings

### ISSUE THREAD

**Issue by UhhClem** [dhanasingh/redmine_wktime#94]
We installed the redmine_ckeditor plugin (https://github.com/a-ono/redmine_ckeditor), having previously installed redmine_wktime, and found that on trying to configure the second plugin's settings for the first time, it caused this error:

Started GET "/settings/plugin/redmine_ckeditor" for 10.10.10.10 at 2017-03-16 15:22:04 -0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_ckeditor"}
  Current user: joe@example.com (id=6)
Completed 500 Internal Server Error in 38ms (ActiveRecord: 26.7ms)

NoMethodError (undefined method `merge!' for false:FalseClass):
  plugins/redmine_wktime/init.rb:222:in `plugin'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

The workaround was to temporarily move the redmine_wktime plugin directory to another location and restart the web server. Then no error occurred with the redmine_ckeditor settings. After simply saving the default settings for the new plugin, we restored the redmine_wktime directory, restarted the web server again, and the settings of all plugins are now accessible.

The problem seems to be that with init.rb:205

                                  @settings = Setting.send "plugin_#{@plugin.id}"

This @settings object will be undefined if settings for some new plugin have never been saved before.

**Comment by dhanasingh** [comment]
Thanks for the detailed info, we will take a look.  Can you give us the versions of the plugin and Redmine you are using ?

**Comment by UhhClem** [comment]
redmine 3.3.1, wktime 2.6.

**Comment by peterdu88** [comment]
Is there any good news for this issue?

**Comment by dhanasingh** [comment]
this is fixed in ERPmine 3.2, please take a look
