### ISSUE TITLE
Entering project settings page causes Error 500

### ISSUE THREAD

**Issue by cancontrols** [dhanasingh/redmine_wktime#95]
Dear all,
thank you for your amazing plugin. nearly everything is working on my bitnami-windows-redmine installation except entering the settings page of a project. In this case an Redmine 500 error pops up and I foundin the production.log following message:

ActionView::Template::Error (undefined method `each' for nil:NilClass):
     6: <th></th>
     7: 	</tr></thead>
     8: 	<tbody>
     9: <% for template in @templates %>
    10: 	<% unless template.new_record? %>
    11: 	<tr class="<%= cycle 'odd', 'even' %>">
    12:     <td><%=h(template.name) %></td><td>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___959685272_92080644'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___959685272_92080644'
  app/helpers/application_helper.rb:324:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___370472130_92051400'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [i386-mingw32]
  Rails version                  4.2.5

I tried versions 2.0, 2.1, 2.6 and 2.7 of your plugin. Could you please give me any kind of idea where to search for the reason? Unfortunately I am completely lost.

Best regards Ulle

**Comment by dhanasingh** [comment]
The log doesn't indicate that it is failing because of ERPmine plugin.  Does it work fine without the ERPmine plugin ?

**Comment by cancontrols** [comment]
Thank you for quick reply. 

Yes everything is working fine without erpmine… I assume I had to disable all other plugins and analyze which combination causes the trouble…

 

Best regards

Ulrich 

 

 

The log doesn't indicate that it is failing because of ERPmine plugin. Does it work fine without the ERPmine plugin ?

**Comment by dhanasingh** [comment]
There could be a version mismatch also the versions 2.2.1+ of ERPmine are compatible with Redmine 3.3

And versions 2.1 and 2.2 versions of ERPmine is compatible with Redmine 3.2

Can you take the right versions and check ?
