### ISSUE TITLE
Translation in some language is wrong

### ISSUE THREAD

**Issue by salmanmp** [dhanasingh/redmine_wktime#96]
Hi
Some languages have different syntax to make "Adjective Noun", and this translation system is wrong for theme. For example "New Payment" in Persian must be translated into "پرداخت جدید" (Payment:پرداخت and New:جدید) but in current translation it is automatically translated into "جدید پرداخت" :))

Thanks a lot

**Comment by CSCSxx** [comment]
Hello salmanmp,
I think the developers would be very happy if you enter the suggestions directly into the appropriate language file (under config/locales) and submit them as a pull request (that's how I do it, and it works great)

**Comment by salmanmp** [comment]
> I think the developers would be very happy if you enter the suggestions directly into the appropriate language file (under config/locales) and submit them as a pull request (that's how I do it, and it works great)

Hi
As I distinguished above, the translation system the developed in this plugin is wrong for "Adjectice Noun". and by adding locale no problem solved.

**Comment by cdhana17** [comment]
We will add this to our current release of Erpmine 4.6

**Comment by cdhana17** [comment]
This issue is fixed in 4.6. 4.6 is released, Please take a look.
